package io.rxmicro.examples.rest.controller.params;

import io.rxmicro.examples.rest.controller.params.model.$$ComplexRequestConstraintValidator;
import io.rxmicro.examples.rest.controller.params.model.$$ComplexRequestServerModelReader;
import io.rxmicro.examples.rest.controller.params.model.$$ComplexResponseConstraintValidator;
import io.rxmicro.examples.rest.controller.params.model.$$ComplexResponseServerModelWriter;
import io.rxmicro.examples.rest.controller.params.model.ComplexRequest;
import io.rxmicro.examples.rest.controller.params.model.ComplexResponse;
import io.rxmicro.http.HttpHeaders;
import io.rxmicro.rest.model.PathVariableMapping;
import io.rxmicro.rest.server.detail.component.AbstractRestController;
import io.rxmicro.rest.server.detail.component.RestControllerRegistrar;
import io.rxmicro.rest.server.detail.model.HttpRequest;
import io.rxmicro.rest.server.detail.model.HttpResponse;
import io.rxmicro.rest.server.detail.model.Registration;
import io.rxmicro.rest.server.detail.model.mapping.ExactUrlRequestMappingRule;

import java.util.List;
import java.util.concurrent.CompletionStage;

import static io.rxmicro.validation.detail.ResponseValidators.validateResponse;

/**
 * Generated by {@code RxMicro Annotation Processor}
 */
public final class $$ComplexModelMicroService extends AbstractRestController {

    private ComplexModelMicroService restController;

    private $$ComplexRequestServerModelReader complexRequestServerModelReader;

    private $$ComplexResponseServerModelWriter complexResponseServerModelWriter;

    private $$ComplexRequestConstraintValidator complexRequestConstraintValidator;

    private $$ComplexResponseConstraintValidator complexResponseConstraintValidator;

    @Override
    protected void postConstruct() {
        restController = new ComplexModelMicroService();
        complexRequestServerModelReader = new $$ComplexRequestServerModelReader();
        complexResponseServerModelWriter = new $$ComplexResponseServerModelWriter(restServerConfig.isHumanReadableOutput());
        complexRequestConstraintValidator = new $$ComplexRequestConstraintValidator();
        complexResponseConstraintValidator = new $$ComplexResponseConstraintValidator();
    }

    @Override
    public Class<?> getRestControllerClass() {
        return ComplexModelMicroService.class;
    }

    @Override
    public void register(final RestControllerRegistrar registrar) {
        registrar.register(
                this,
                new Registration(
                        "/",
                        "handle",
                        List.of(
                                io.rxmicro.examples.rest.controller.params.model.ComplexRequest.class
                        ),
                        this::handle,
                        false,
                        new ExactUrlRequestMappingRule(
                                "POST",
                                "/",
                                true
                        )
                )
        );
    }

    private CompletionStage<HttpResponse> handle(final PathVariableMapping pathVariableMapping,
                                                 final HttpRequest request) {
        final ComplexRequest req = complexRequestServerModelReader.read(pathVariableMapping, request, request.isContentPresent());
        complexRequestConstraintValidator.validate(req);
        final HttpHeaders headers = HttpHeaders.of();
        return restController.handle(req)
                .thenApply(response -> buildResponse(response, 200, headers));
    }

    private HttpResponse buildResponse(final ComplexResponse model,
                                       final int statusCode,
                                       final HttpHeaders headers) {
        validateResponse(restServerConfig.isEnableAdditionalValidations(), complexResponseConstraintValidator, model);
        final HttpResponse response = httpResponseBuilder.build();
        response.setStatus(statusCode);
        response.setOrAddHeaders(headers);
        complexResponseServerModelWriter.write(model, response);
        return response;
    }
}
