package io.rxmicro.examples.rest.controller.params;

import io.rxmicro.http.HttpHeaders;
import io.rxmicro.rest.model.PathVariableMapping;
import io.rxmicro.rest.server.detail.component.AbstractRestController;
import io.rxmicro.rest.server.detail.component.RestControllerRegistrar;
import io.rxmicro.rest.server.detail.model.HttpRequest;
import io.rxmicro.rest.server.detail.model.HttpResponse;
import io.rxmicro.rest.server.detail.model.Registration;
import io.rxmicro.rest.server.detail.model.mapping.ExactUrlRequestMappingRule;

import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;

/**
 * Generated by {@code RxMicro Annotation Processor}
 */
public final class $$ListQueryParamMicroService extends AbstractRestController {

    private ListQueryParamMicroService restController;

    private $$VirtualListQueryParamRequestServerModelReader virtualListQueryParamRequestServerModelReader;

    private $$VirtualListQueryParamRequestConstraintValidator virtualListQueryParamRequestConstraintValidator;

    @Override
    protected void postConstruct() {
        restController = new ListQueryParamMicroService();
        virtualListQueryParamRequestServerModelReader = new $$VirtualListQueryParamRequestServerModelReader();
        virtualListQueryParamRequestConstraintValidator = new $$VirtualListQueryParamRequestConstraintValidator();
    }

    @Override
    public Class<?> getRestControllerClass() {
        return ListQueryParamMicroService.class;
    }

    @Override
    public void register(final RestControllerRegistrar registrar) {
        registrar.register(
                this,
                new Registration(
                        "/",
                        "consume",
                        List.of(
                                java.util.List.class
                        ),
                        this::consume,
                        false,
                        new ExactUrlRequestMappingRule(
                                "GET",
                                "/",
                                false
                        )
                )
        );
    }

    private CompletionStage<HttpResponse> consume(final PathVariableMapping pathVariableMapping,
                                                  final HttpRequest request) {
        final $$VirtualListQueryParamRequest req = virtualListQueryParamRequestServerModelReader.read(pathVariableMapping, request, request.isContentPresent());
        virtualListQueryParamRequestConstraintValidator.validate(req);
        final HttpHeaders headers = HttpHeaders.of();
        restController.consume(req.supportedStatuses);
        return CompletableFuture.completedStage(buildResponse(200, headers));
    }

    private HttpResponse buildResponse(final int statusCode,
                                       final HttpHeaders headers) {
        final HttpResponse response = httpResponseBuilder.build();
        response.setStatus(statusCode);
        response.setOrAddHeaders(headers);
        return response;
    }
}
