package io.rxmicro.examples.rest.client.path.variables;

/**
 * Generated by {@code RxMicro Annotation Processor}
 */
public final class $$VirtualRESTRequest {

    // Path variables
    final String category;

    final String type;

    final String subType;

    $$VirtualRESTRequest(final String category, final String type, final String subType) {
        this.category = category;
        this.type = type;
        this.subType = subType;
    }
}
