package io.rxmicro.examples.data.mongo.all.operations.model;

import io.rxmicro.data.mongo.detail.EntityToMongoDBConverter;
import org.bson.Document;

/**
 * Generated by rxmicro annotation processor
 *
 * @link https://rxmicro.io
 */
public final class $$AccountDocumentEntityToMongoDBConverter extends EntityToMongoDBConverter<AccountDocument, Document> {

    @Override
    public Document toDB(final AccountDocument model,
                         final boolean withId) {
        final Document document = new Document();
        document.append("email", model.email);
        document.append("firstName", model.firstName);
        document.append("lastName", model.lastName);
        document.append("balance", model.balance);
        return document;
    }

}
