package io.rxmicro.examples.validation.server.extendable.model.child_model_without_fields.grand;

import io.rxmicro.exchange.json.detail.ModelToJsonConverter;
import io.rxmicro.json.JsonObjectBuilder;

/**
 * Generated by {@code RxMicro Annotation Processor}
 */
public final class $$GrandParentModelToJsonConverter extends ModelToJsonConverter<GrandParent> {

    public void putValuesToBuilder(final GrandParent model,
                                   final JsonObjectBuilder builder) {
        builder.put("grandParameter", model.grandParameter);
    }
}
