package io.rxmicro.examples.rest.client.model.fields.internals.reflection;

import io.rxmicro.http.client.ClientHttpResponse;
import io.rxmicro.rest.client.detail.ModelReader;

import static rxmicro.$$Reflections.setFieldValue;

/**
 * Generated by rxmicro annotation processor
 *
 * @link https://rxmicro.io
 */
public final class $$ResponseModelReader extends ModelReader<Response> {

    @Override
    public Response readSingle(final ClientHttpResponse response) {
        final Response model = new Response();
        setFieldValue(model, "status", response.statusCode());
        setFieldValue(model, "version", response.version());
        setFieldValue(model, "headers", response.headers());
        setFieldValue(model, "body", response.bodyAsBytes());
        return model;
    }
}
