package io.rxmicro.examples.rest.client.model.field.access.internals.gettersetter;

import io.rxmicro.rest.client.detail.ClientModelReader;
import io.rxmicro.rest.client.detail.HttpResponse;

/**
 * Generated by {@code RxMicro Annotation Processor}
 */
public final class $$ResponseClientModelReader extends ClientModelReader<Response> {

    @Override
    public Response readSingle(final HttpResponse response) {
        final Response model = new Response();
        readPrimitivesToModel(response, model);
        return model;
    }

    protected void readPrimitivesToModel(final HttpResponse response,
                                         final Response model) {
        model.setInternalResponseStatusCode(response.getStatusCode());
        model.setInternalHttpVersion(response.getVersion());
        model.setInternalHttpHeaders(response.getHeaders());
        model.setInternalResponseBody(response.getBodyAsBytes());
    }
}
