package io.rxmicro.examples.rest.controller.extendable.model.request.all_body.all_models_contain_nested_fields.child;

import io.rxmicro.examples.rest.controller.extendable.model.request.all_body.all_models_contain_nested_fields.child.nested.$$NestedConstraintValidator;
import io.rxmicro.examples.rest.controller.extendable.model.request.all_body.all_models_contain_nested_fields.parent.$$ParentConstraintValidator;
import io.rxmicro.model.ModelType;
import io.rxmicro.rest.model.HttpModelType;
import io.rxmicro.validation.ConstraintValidator;
import io.rxmicro.validation.validator.NotEmptyStringConstraintValidator;
import io.rxmicro.validation.validator.RequiredAndNotEmptyStringConstraintValidator;
import io.rxmicro.validation.validator.RequiredConstraintValidator;

import static io.rxmicro.validation.detail.StatelessValidators.getStatelessValidator;

/**
 * Generated by {@code RxMicro Annotation Processor}
 */
public final class $$ChildConstraintValidator implements ConstraintValidator<Child> {

    private final $$ParentConstraintValidator parentValidator =
            new $$ParentConstraintValidator();

    private final $$NestedConstraintValidator nestedConstraintValidator =
            new $$NestedConstraintValidator();

    private final NotEmptyStringConstraintValidator notEmptyStringConstraintValidator =
            getStatelessValidator(NotEmptyStringConstraintValidator.class);

    private final RequiredAndNotEmptyStringConstraintValidator requiredAndNotEmptyStringConstraintValidator =
            getStatelessValidator(RequiredAndNotEmptyStringConstraintValidator.class);

    private final RequiredConstraintValidator requiredConstraintValidator =
            getStatelessValidator(RequiredConstraintValidator.class);

    @Override
    public void validateNonNull(final Child model,
                                final ModelType httpModelType,
                                final String name) {
        parentValidator.validate(model, httpModelType, name);
        notEmptyStringConstraintValidator.validate(model.childVar, HttpModelType.PATH, "childVar");

        requiredAndNotEmptyStringConstraintValidator.validate(model.childHeader, HttpModelType.HEADER, "childHeader");

        requiredAndNotEmptyStringConstraintValidator.validate(model.childParameter, HttpModelType.PARAMETER, "childParameter");

        requiredConstraintValidator.validate(model.childNestedParameter, HttpModelType.PARAMETER, "childNestedParameter");
        nestedConstraintValidator.validate(model.childNestedParameter, HttpModelType.PARAMETER, "childNestedParameter");
    }
}
