package io.rxmicro.examples.data.mongo.basic.model;

import io.rxmicro.data.mongo.detail.EntityFromMongoDBConverter;
import org.bson.Document;

/**
 * Generated by rxmicro annotation processor
 *
 * @link http://rxmicro.io
 */
public final class $$AccountEntityFromMongoDBConverter extends EntityFromMongoDBConverter<Document, Account> {

    @Override
    public Account fromDB(final Document document) {
        final Account model = new Account();
        model.firstName = toString(document.get("firstName"), "firstName");
        model.lastName = toString(document.get("lastName"), "lastName");
        return model;
    }
}
