package io.rxmicro.examples.rest.controller.model.fields;

import io.rxmicro.http.HttpHeaders;
import io.rxmicro.http.QueryParams;
import io.rxmicro.rest.model.HttpModelType;
import io.rxmicro.rest.model.PathVariableMapping;
import io.rxmicro.rest.server.detail.component.ModelReader;
import io.rxmicro.rest.server.detail.model.HttpRequest;

/**
 * Generated by rxmicro annotation processor
 *
 * @link https://rxmicro.io
 */
public final class $$VirtualMappingStrategyRequest2ModelReader extends ModelReader<$$VirtualMappingStrategyRequest2> {

    @Override
    public $$VirtualMappingStrategyRequest2 read(final PathVariableMapping pathVariableMapping,
                                                 final HttpRequest request,
                                                 final boolean readParametersFromBody) {
        final $$VirtualMappingStrategyRequest2 model = new $$VirtualMappingStrategyRequest2();
        final HttpHeaders httpHeaders = request.getHeaders();
        model.supportedApiVersionCode = toBigDecimal(httpHeaders.getValue("Supported_Api_Version_Code"), HttpModelType.header, "Supported_Api_Version_Code");
        final QueryParams params = extractParams(request.getQueryString());
        model.maxSupportedDateTime = toInstant(params.getValue("max_supported_date_time"), HttpModelType.parameter, "max_supported_date_time");
        return model;
    }
}
