package io.rxmicro.examples.rest.controller.model.fields;

import io.rxmicro.http.HttpHeaders;
import io.rxmicro.http.QueryParams;
import io.rxmicro.rest.model.HttpModelType;
import io.rxmicro.rest.model.PathVariableMapping;
import io.rxmicro.rest.server.detail.component.ModelReader;
import io.rxmicro.rest.server.detail.model.HttpRequest;

/**
 * Generated by rxmicro annotation processor
 *
 * @link https://rxmicro.io
 */
public final class $$VirtualMappingStrategyRequest3ModelReader extends ModelReader<$$VirtualMappingStrategyRequest3> {

    @Override
    public $$VirtualMappingStrategyRequest3 read(final PathVariableMapping pathVariableMapping,
                                                 final HttpRequest request,
                                                 final boolean readParametersFromBody) {
        final $$VirtualMappingStrategyRequest3 model = new $$VirtualMappingStrategyRequest3();
        final HttpHeaders httpHeaders = request.getHeaders();
        model.supportedApiVersionCode = toBigDecimal(httpHeaders.getValue("Supported-Api-Version-Code"), HttpModelType.header, "Supported-Api-Version-Code");
        final QueryParams params = extractParams(request.getQueryString());
        model.maxSupportedDateTime = toInstant(params.getValue("max-supported-date-time"), HttpModelType.parameter, "max-supported-date-time");
        return model;
    }
}
