package io.rxmicro.examples.rest.controller.model.fields;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * Generated by rxmicro annotation processor
 */
public final class $$VirtualMappingStrategyRequest {

    // Headers
    BigDecimal supportedApiVersionCode;

    // Parameters
    Instant maxSupportedDateTime;

}
