package rxmicro;

import io.rxmicro.cdi.detail.InternalBeanFactory;
import io.rxmicro.examples.cdi.resource.basic.$$ComponentBeanSupplier;
import io.rxmicro.examples.cdi.resource.basic.Component;
import io.rxmicro.runtime.detail.ByTypeInstanceQualifier;

import static io.rxmicro.common.detail.Customizers.invokeStaticSection;

/**
 * Generated by {@code RxMicro Annotation Processor}
 */
public final class $$BeanFactoryImpl extends InternalBeanFactory {

    static {
        invokeStaticSection($$EnvironmentCustomizer.class);
    }

    public $$BeanFactoryImpl() {
        register(
                Component.class, new $$ComponentBeanSupplier(),
                new ByTypeInstanceQualifier<>(Component.class)
        );
    }
}
