package io.rxmicro.examples.rest.controller.extendable.model.request.any_body.path_body_header.parent;

import io.rxmicro.exchange.json.detail.ModelFromJsonConverter;

import java.util.Map;

/**
 * Generated by {@code RxMicro Annotation Processor}
 */
public final class $$ParentModelFromJsonConverter extends ModelFromJsonConverter<Parent> {

    @Override
    public Parent fromJsonObject(final Map<String, Object> params) {
        final Parent model = new Parent();
        readParamsToModel(params, model);
        return model;
    }

    public void readParamsToModel(final Map<String, Object> params,
                                  final Parent model) {
        model.parentParameter = toString(params.get("parentParameter"), "parentParameter");
    }
}
