package io.rxmicro.examples.validation.server.basic;

/**
 * Generated by rxmicro annotation processor
 *
 * @link https://rxmicro.io
 */
public final class $$VirtualRequest {

    // Parameters
    String email;

}
