package io.rxmicro.examples.rest.controller.map.model.type.model;

import io.rxmicro.examples.rest.controller.map.model.type.model.nested.$$NestedModelFromJsonConverter;
import io.rxmicro.exchange.json.detail.ModelFromJsonConverter;

import java.util.Map;

/**
 * Generated by {@code RxMicro Annotation Processor}
 */
public final class $$ModelModelFromJsonConverter extends ModelFromJsonConverter<Model> {

    private final $$NestedModelFromJsonConverter nestedModelFromJsonConverter =
            new $$NestedModelFromJsonConverter();

    @Override
    public Model fromJsonObject(final Map<String, Object> params) {
        final Model model = new Model();
        model.nested = convertToMapIfNotNull(nestedModelFromJsonConverter, params.get("nested"), "nested");
        return model;
    }
}
