package io.rxmicro.examples.rest.controller.model.field.access.internals.gettersetter;

import io.rxmicro.rest.model.PathVariableMapping;
import io.rxmicro.rest.server.detail.component.ModelReader;
import io.rxmicro.rest.server.detail.model.HttpRequest;

/**
 * Generated by {@code RxMicro Annotation Processor}
 */
public final class $$RequestModelReader extends ModelReader<Request> {

    @Override
    public Request read(final PathVariableMapping pathVariableMapping,
                        final HttpRequest request,
                        final boolean readParametersFromBody) {
        final Request model = new Request();
        readPrimitivesToModel(pathVariableMapping, request, model);
        return model;
    }

    protected void readPrimitivesToModel(final PathVariableMapping pathVariableMapping,
                                         final HttpRequest request,
                                         final Request model) {
        model.setInternalRemoteAddress1(String.valueOf(request.getRemoteAddress()));
        model.setInternalRemoteAddress2(request.getRemoteAddress());
        model.setInternalUrlPath(request.getUri());
        model.setInternalRequestMethod(request.getMethod());
        model.setInternalHttpVersion(request.getVersion());
        model.setInternalRequestHeaders(request.getHeaders());
        model.setInternalRequestBody(request.getContent());
        model.setInternalRequest(request);
    }
}
