package io.rxmicro.examples.rest.controller.routing;

import io.rxmicro.http.QueryParams;
import io.rxmicro.rest.model.HttpModelType;
import io.rxmicro.rest.model.PathVariableMapping;
import io.rxmicro.rest.server.detail.component.ModelReader;
import io.rxmicro.rest.server.detail.model.HttpRequest;

/**
 * Generated by {@code RxMicro Annotation Processor}
 */
public final class $$VirtualRoutingUsingHttpBodyRequestModelReader extends ModelReader<$$VirtualRoutingUsingHttpBodyRequest> {

    @Override
    public $$VirtualRoutingUsingHttpBodyRequest read(final PathVariableMapping pathVariableMapping,
                                                     final HttpRequest request,
                                                     final boolean readParametersFromBody) {
        final $$VirtualRoutingUsingHttpBodyRequest model = new $$VirtualRoutingUsingHttpBodyRequest();
        final QueryParams params = extractParams(request.getQueryString());
        readPrimitivesToModel(pathVariableMapping, request, params, model, readParametersFromBody);
        return model;
    }

    public void readPrimitivesToModel(final PathVariableMapping pathVariableMapping,
                                      final HttpRequest request,
                                      final QueryParams params,
                                      final $$VirtualRoutingUsingHttpBodyRequest model,
                                      final boolean readParametersFromBody) {
        model.parameter = toString(params.getValue("parameter"), HttpModelType.PARAMETER, "parameter");
    }
}
