package io.rxmicro.examples.rest.controller.routing;

import io.rxmicro.exchange.json.detail.ModelFromJsonConverter;

import java.util.Map;

/**
 * Generated by rxmicro annotation processor
 *
 * @link https://rxmicro.io
 */
public final class $$VirtualRoutingUsingHttpBodyRequest2ModelFromJsonConverter extends ModelFromJsonConverter<$$VirtualRoutingUsingHttpBodyRequest2> {

    @Override
    public $$VirtualRoutingUsingHttpBodyRequest2 fromJsonObject(final Map<String, Object> params) {
        final $$VirtualRoutingUsingHttpBodyRequest2 model = new $$VirtualRoutingUsingHttpBodyRequest2();
        model.parameter = toString(params.get("parameter"), "parameter");
        return model;
    }
}
