package io.rxmicro.examples.rest.controller.extendable.model.response.all.all_models_contain_nested_fields.grand;

import io.rxmicro.examples.rest.controller.extendable.model.response.all.all_models_contain_nested_fields.grand.nested.$$NestedConstraintValidator;
import io.rxmicro.model.ModelType;
import io.rxmicro.rest.model.HttpModelType;
import io.rxmicro.validation.ConstraintValidator;
import io.rxmicro.validation.validator.RequiredAndNotEmptyStringConstraintValidator;
import io.rxmicro.validation.validator.RequiredConstraintValidator;

import static io.rxmicro.validation.detail.StatelessValidators.getStatelessValidator;

/**
 * Generated by {@code RxMicro Annotation Processor}
 */
public final class $$GrandParentConstraintValidator implements ConstraintValidator<GrandParent> {

    private final $$NestedConstraintValidator nestedConstraintValidator =
            new $$NestedConstraintValidator();

    private final RequiredAndNotEmptyStringConstraintValidator requiredAndNotEmptyStringConstraintValidator =
            getStatelessValidator(RequiredAndNotEmptyStringConstraintValidator.class);

    private final RequiredConstraintValidator requiredConstraintValidator =
            getStatelessValidator(RequiredConstraintValidator.class);

    @Override
    public void validateNonNull(final GrandParent model,
                                final ModelType httpModelType,
                                final String name) {
        requiredAndNotEmptyStringConstraintValidator.validate(model.grandHeader, HttpModelType.HEADER, "grandHeader");

        requiredAndNotEmptyStringConstraintValidator.validate(model.grandParameter, HttpModelType.PARAMETER, "grandParameter");

        requiredConstraintValidator.validate(model.grandNestedParameter, HttpModelType.PARAMETER, "grandNestedParameter");
        nestedConstraintValidator.validate(model.grandNestedParameter, HttpModelType.PARAMETER, "grandNestedParameter");
    }
}
