package io.rxmicro.examples.rest.controller.handlers;

/**
 * Generated by rxmicro annotation processor
 *
 * @link http://rxmicro.io
 */
public final class $$VirtualWithBodyRequest7 {

    // Parameters
    String requestParameter;

}
