package io.rxmicro.examples.rest.controller.handlers;

/**
 * Generated by rxmicro annotation processor
 */
public final class $$VirtualWithoutBodyRequest2 {

    // Parameters
    String requestParameter;

}
