package io.rxmicro.examples.rest.controller.handlers;

/**
 * Generated by {@code RxMicro Annotation Processor}
 */
public final class $$VirtualWithBodyRequest2 {

    // Parameters
    String requestParameter;

}
