package io.rxmicro.examples.rest.controller.model.field.access.internals.direct;

import io.rxmicro.rest.server.detail.component.ServerModelWriter;
import io.rxmicro.rest.server.detail.model.HttpResponse;

/**
 * Generated by {@code RxMicro Annotation Processor}
 */
public final class $$ResponseServerModelWriter extends ServerModelWriter<Response> {

    public $$ResponseServerModelWriter(final boolean humanReadableOutput) {
        //do nothing
    }

    @Override
    public void write(final Response model,
                      final HttpResponse response) {
        writePrimitivesToResponse(model, response);
    }

    public void writePrimitivesToResponse(final Response model,
                                          final HttpResponse response) {
        response.setStatus(model.internalResponseStatusCode);
        response.setVersion(model.internalHttpVersion);
        response.setOrAddHeaders(model.internalHttpHeaders);
        response.setContent(model.internalResponseBody);
    }
}
