package io.rxmicro.examples.rest.client.model.fields;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * Generated by rxmicro annotation processor
 *
 * @link https://rxmicro.io
 */
public final class $$VirtualMappingStrategyRequest2 {

    // Headers
    final BigDecimal supportedApiVersionCode;

    // Parameters
    final Instant maxSupportedDateTime;

    $$VirtualMappingStrategyRequest2(final BigDecimal supportedApiVersionCode, final Instant maxSupportedDateTime) {
        this.supportedApiVersionCode = supportedApiVersionCode;
        this.maxSupportedDateTime = maxSupportedDateTime;
    }
}
