package io.rxmicro.examples.rest.controller.model.field.access.params;

import io.rxmicro.examples.rest.controller.model.field.access.Status;
import io.rxmicro.examples.rest.controller.model.field.access.params.direct.nested.Nested;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Generated by {@code RxMicro Annotation Processor}
 */
public final class $$VirtualVirtualParamsRequest2 {

    // Parameters
    Boolean booleanParameter;

    Byte byteParameter;

    Short shortParameter;

    Integer intParameter;

    Long longParameter;

    BigInteger bigIntParameter;

    Float floatParameter;

    Double doubleParameter;

    BigDecimal decimalParameter;

    Character charParameter;

    String stringParameter;

    Instant instantParameter;

    Status enumParameter;

    List<Boolean> booleanParameterList;

    List<Byte> byteParameterList;

    List<Short> shortParameterList;

    List<Integer> intParameterList;

    List<Long> longParameterList;

    List<BigInteger> bigIntParameterList;

    List<Float> floatParameterList;

    List<Double> doubleParameterList;

    List<BigDecimal> decimalParameterList;

    List<Character> charParameterList;

    List<String> stringParameterList;

    List<Instant> instantParameterList;

    List<Status> enumParameterList;

    Set<Boolean> booleanParameterSet;

    Set<Byte> byteParameterSet;

    Set<Short> shortParameterSet;

    Set<Integer> intParameterSet;

    Set<Long> longParameterSet;

    Set<BigInteger> bigIntParameterSet;

    Set<Float> floatParameterSet;

    Set<Double> doubleParameterSet;

    Set<BigDecimal> decimalParameterSet;

    Set<Character> charParameterSet;

    Set<String> stringParameterSet;

    Set<Instant> instantParameterSet;

    Set<Status> enumParameterSet;

    Map<String, Boolean> booleanParameterMap;

    Map<String, Byte> byteParameterMap;

    Map<String, Short> shortParameterMap;

    Map<String, Integer> integerParameterMap;

    Map<String, Long> longParameterMap;

    Map<String, BigInteger> bigIntegerParameterMap;

    Map<String, Float> floatParameterMap;

    Map<String, Double> doubleParameterMap;

    Map<String, BigDecimal> bigDecimalParameterMap;

    Map<String, Character> characterParameterMap;

    Map<String, String> stringParameterMap;

    Map<String, Instant> instantParameterMap;

    Map<String, Status> enumParameterMap;

    Nested nested;

    List<Nested> nestedList;

    Set<Nested> nestedSet;

    Map<String, Nested> nestedParameterMap;

}
