package io.rxmicro.examples.rest.controller.redirect;

import io.rxmicro.exchange.json.detail.ModelFromJsonConverter;

import java.util.Map;

/**
 * Generated by rxmicro annotation processor
 *
 * @link http://rxmicro.io
 */
public final class $$VirtualRequestModelFromJsonConverter extends ModelFromJsonConverter<$$VirtualRequest> {

    @Override
    public $$VirtualRequest fromJsonObject(final Map<String, Object> params) {
        final $$VirtualRequest model = new $$VirtualRequest();
        model.parameter = toString(params.get("parameter"), "parameter");
        return model;
    }
}
