package io.rxmicro.examples.rest.controller.params.model;

import io.rxmicro.exchange.json.detail.JsonExchangeDataFormatConverter;
import io.rxmicro.rest.detail.ExchangeDataFormatConverter;
import io.rxmicro.rest.model.PathVariableMapping;
import io.rxmicro.rest.server.detail.component.ModelReader;
import io.rxmicro.rest.server.detail.model.HttpRequest;

/**
 * Generated by rxmicro annotation processor
 *
 * @link https://rxmicro.io
 */
public final class $$ComplexRequestModelReader extends ModelReader<ComplexRequest> {

    private final ExchangeDataFormatConverter<Object> exchangeDataFormatConverter =
            new JsonExchangeDataFormatConverter(false);

    private final $$ComplexRequestModelFromJsonConverter complexRequestModelFromJsonConverter =
            new $$ComplexRequestModelFromJsonConverter();

    @Override
    public ComplexRequest read(final PathVariableMapping pathVariableMapping,
                               final HttpRequest request,
                               final boolean readParametersFromBody) {
        final Object body = exchangeDataFormatConverter.fromBytes(request.getContent());
        final ComplexRequest model = complexRequestModelFromJsonConverter.fromJsonObject(body);
        return model;
    }
}
