package io.rxmicro.examples.data.r2dbc.postgresql.request.id.supplier;

import io.r2dbc.pool.ConnectionPool;
import io.reactivex.rxjava3.core.Single;
import io.rxmicro.data.sql.model.IsolationLevel;
import io.rxmicro.data.sql.model.rxjava3.Transaction;
import io.rxmicro.data.sql.r2dbc.detail.RepositoryConnectionFactory;
import io.rxmicro.data.sql.r2dbc.detail.RepositoryConnectionPool;
import io.rxmicro.data.sql.r2dbc.postgresql.detail.AbstractPostgreSQLRepository;
import io.rxmicro.logger.RequestIdSupplier;

/**
 * Generated by {@code RxMicro Annotation Processor}
 */
public final class $$PostgreSQLBeginRxJava3TransactionRepository extends AbstractPostgreSQLRepository implements BeginRxJava3TransactionRepository {

    private final RepositoryConnectionFactory connectionFactory;

    public $$PostgreSQLBeginRxJava3TransactionRepository(final ConnectionPool pool) {
        super(BeginRxJava3TransactionRepository.class);
        this.connectionFactory = new RepositoryConnectionPool(BeginRxJava3TransactionRepository.class, pool);
    }

    @Override
    public Single<Transaction> beginTransaction(final RequestIdSupplier requestIdSupplier) {
        return Single.fromPublisher(
                this.connectionFactory.create(requestIdSupplier)
                        .flatMap(c -> beginRxJava3Transaction(c))
        );
    }

    @Override
    public Single<Transaction> beginTransaction(final IsolationLevel isolationLevel, final RequestIdSupplier requestIdSupplier) {
        return Single.fromPublisher(this.connectionFactory.create(requestIdSupplier).flatMap(c -> beginRxJava3Transaction(c)))
                        .flatMap(t -> t.setIsolationLevel(isolationLevel)
                                .andThen(Single.just(t)));
    }

    @Override
    public Single<Transaction> beginTransaction(final RequestIdSupplier requestIdSupplier, final IsolationLevel isolationLevel) {
        return Single.fromPublisher(this.connectionFactory.create(requestIdSupplier).flatMap(c -> beginRxJava3Transaction(c)))
                        .flatMap(t -> t.setIsolationLevel(isolationLevel)
                                .andThen(Single.just(t)));
    }
}
