package io.rxmicro.examples.data.mongo.update.model;

import io.rxmicro.data.mongo.detail.EntityToMongoDBConverter;
import org.bson.Document;

/**
 * Generated by rxmicro annotation processor
 *
 * @link https://rxmicro.io
 */
public final class $$AccountEntityEntityToMongoDBConverter extends EntityToMongoDBConverter<AccountEntity, Document> {

    @Override
    public Document toDB(final AccountEntity model,
                         final boolean withId) {
        final Document document = new Document();
        document.append("email", model.email);
        document.append("firstName", model.firstName);
        document.append("lastName", model.lastName);
        document.append("balance", model.balance);
        final Object id = model.id;
        if (id != null && withId) {
            document.append("_id", id);
        }
        return document;
    }

    @Override
    public Object getId(final AccountEntity model) {
        return require(model.id, "Entity does not contain document id: ?", model);
    }

    @Override
    public void setId(final Document document,
                      final AccountEntity model) {
        final Object id = document.get("_id");
        if (id != null) {
            model.id = toLong(id, "id");
        }
    }
}
