package io.rxmicro.examples.validation.client.all.types.model;

import io.rxmicro.exchange.json.detail.ModelToJsonConverter;
import io.rxmicro.json.JsonObjectBuilder;
import org.junit.runner.Request;

import java.util.Map;

/**
 * Generated by {@code RxMicro Annotation Processor}
 */
public final class $$RequestModelToJsonConverter extends ModelToJsonConverter<Request> {

    @Override
    public Map<String, Object> toJsonObject(final Request model) {
        final JsonObjectBuilder builder = new JsonObjectBuilder();
        putValuesToBuilder(model, builder);
        return builder.build();
    }

    public void putValuesToBuilder(final Request model,
                                   final JsonObjectBuilder builder) {
        builder.put("email", model.email);
    }
}
