package io.rxmicro.examples.validation.server.extendable.model.all_models_contain_fields.parent;

import io.rxmicro.examples.validation.server.extendable.model.all_models_contain_fields.grand.$$GrandParentConstraintValidator;
import io.rxmicro.rest.model.HttpModelType;
import io.rxmicro.validation.ConstraintValidator;
import io.rxmicro.validation.validator.RequiredAndNotEmptyStringConstraintValidator;
import io.rxmicro.validation.validator.UppercaseConstraintValidator;

import static io.rxmicro.validation.detail.StatelessValidators.getStatelessValidator;

/**
 * Generated by {@code RxMicro Annotation Processor}
 */
public final class $$ParentConstraintValidator implements ConstraintValidator<Parent> {

    private final $$GrandParentConstraintValidator parentValidator =
            new $$GrandParentConstraintValidator();

    private final RequiredAndNotEmptyStringConstraintValidator requiredAndNotEmptyStringConstraintValidator =
            getStatelessValidator(RequiredAndNotEmptyStringConstraintValidator.class);

    private final UppercaseConstraintValidator uppercaseConstraintValidator =
            getStatelessValidator(UppercaseConstraintValidator.class);

    @Override
    public void validateNonNull(final Parent model,
                                final HttpModelType httpModelType,
                                final String name) {
        parentValidator.validate(model, httpModelType, name);
        requiredAndNotEmptyStringConstraintValidator.validate(model.parentParameter, HttpModelType.PARAMETER, "parentParameter");
        uppercaseConstraintValidator.validate(model.parentParameter, HttpModelType.PARAMETER, "parentParameter");
    }
}
