package io.rxmicro.examples.rest.client.handlers;

/**
 * Generated by {@code RxMicro Annotation Processor}
 */
public final class $$VirtualWithoutBodyRequest3 {

    // Parameters
    final String requestParameter;

    $$VirtualWithoutBodyRequest3(final String requestParameter) {
        this.requestParameter = requestParameter;
    }
}
