package io.rxmicro.examples.rest.client.handlers;

/**
 * Generated by rxmicro annotation processor
 *
 * @link https://rxmicro.io
 */
public final class $$VirtualWithBodyRequest2 {

    // Parameters
    final String requestParameter;

    $$VirtualWithBodyRequest2(final String requestParameter) {
        this.requestParameter = requestParameter;
    }
}
