package io.rxmicro.examples.rest.client.handlers;

/**
 * Generated by rxmicro annotation processor
 *
 * @link http://rxmicro.io
 */
public final class $$VirtualWithBodyRequest4 {

    // Parameters
    final String requestParameter;

    $$VirtualWithBodyRequest4(final String requestParameter) {
        this.requestParameter = requestParameter;
    }
}
