package io.rxmicro.examples.validation.server.all.standard;

import io.rxmicro.examples.validation.server.all.standard.model.Color;
import io.rxmicro.http.error.ValidationException;
import io.rxmicro.rest.model.HttpModelType;
import io.rxmicro.validation.ConstraintValidator;
import io.rxmicro.validation.base.LocationAccuracy;
import io.rxmicro.validation.constraint.Base64URLEncoded.Alphabet;
import io.rxmicro.validation.constraint.CountryCode.Format;
import io.rxmicro.validation.constraint.IP.Version;
import io.rxmicro.validation.constraint.TruncatedTime.Truncated;
import io.rxmicro.validation.validator.AssertFalseConstraintValidator;
import io.rxmicro.validation.validator.AssertTrueConstraintValidator;
import io.rxmicro.validation.validator.Base64URLEncodedConstraintValidator;
import io.rxmicro.validation.validator.CountryCodeConstraintValidator;
import io.rxmicro.validation.validator.EmailConstraintValidator;
import io.rxmicro.validation.validator.EnumerationCharacterConstraintValidator;
import io.rxmicro.validation.validator.EnumerationStringConstraintValidator;
import io.rxmicro.validation.validator.FutureInstantConstraintValidator;
import io.rxmicro.validation.validator.FutureOrPresentInstantConstraintValidator;
import io.rxmicro.validation.validator.HostNameConstraintValidator;
import io.rxmicro.validation.validator.IPConstraintValidator;
import io.rxmicro.validation.validator.LatConstraintValidator;
import io.rxmicro.validation.validator.LatinAlphabetOnlyConstraintValidator;
import io.rxmicro.validation.validator.LengthConstraintValidator;
import io.rxmicro.validation.validator.LngConstraintValidator;
import io.rxmicro.validation.validator.LowercaseConstraintValidator;
import io.rxmicro.validation.validator.MaxBigDecimalNumberConstraintValidator;
import io.rxmicro.validation.validator.MaxBigIntegerNumberConstraintValidator;
import io.rxmicro.validation.validator.MaxByteConstraintValidator;
import io.rxmicro.validation.validator.MaxDoubleConstraintValidator;
import io.rxmicro.validation.validator.MaxFloatConstraintValidator;
import io.rxmicro.validation.validator.MaxIntConstraintValidator;
import io.rxmicro.validation.validator.MaxLengthConstraintValidator;
import io.rxmicro.validation.validator.MaxLongConstraintValidator;
import io.rxmicro.validation.validator.MaxShortConstraintValidator;
import io.rxmicro.validation.validator.MaxSizeConstraintValidator;
import io.rxmicro.validation.validator.MinBigDecimalNumberConstraintValidator;
import io.rxmicro.validation.validator.MinBigIntegerNumberConstraintValidator;
import io.rxmicro.validation.validator.MinByteConstraintValidator;
import io.rxmicro.validation.validator.MinDoubleConstraintValidator;
import io.rxmicro.validation.validator.MinFloatConstraintValidator;
import io.rxmicro.validation.validator.MinIntConstraintValidator;
import io.rxmicro.validation.validator.MinLengthConstraintValidator;
import io.rxmicro.validation.validator.MinLongConstraintValidator;
import io.rxmicro.validation.validator.MinShortConstraintValidator;
import io.rxmicro.validation.validator.MinSizeConstraintValidator;
import io.rxmicro.validation.validator.NotEmptyStringConstraintValidator;
import io.rxmicro.validation.validator.NumericConstraintValidator;
import io.rxmicro.validation.validator.PastInstantConstraintValidator;
import io.rxmicro.validation.validator.PastOrPresentInstantConstraintValidator;
import io.rxmicro.validation.validator.PatternConstraintValidator;
import io.rxmicro.validation.validator.PhoneConstraintValidator;
import io.rxmicro.validation.validator.RequiredAndNotEmptyStringConstraintValidator;
import io.rxmicro.validation.validator.RequiredConstraintValidator;
import io.rxmicro.validation.validator.RequiredListConstraintValidator;
import io.rxmicro.validation.validator.SizeConstraintValidator;
import io.rxmicro.validation.validator.SkypeConstraintValidator;
import io.rxmicro.validation.validator.SubEnumConstraintValidator;
import io.rxmicro.validation.validator.TelegramConstraintValidator;
import io.rxmicro.validation.validator.TruncatedTimeInstantConstraintValidator;
import io.rxmicro.validation.validator.URIConstraintValidator;
import io.rxmicro.validation.validator.URLEncodedConstraintValidator;
import io.rxmicro.validation.validator.UniqueItemsConstraintValidator;
import io.rxmicro.validation.validator.UppercaseConstraintValidator;
import io.rxmicro.validation.validator.ViberConstraintValidator;
import io.rxmicro.validation.validator.WhatsAppConstraintValidator;

import java.util.List;

import static io.rxmicro.validation.detail.StatelessValidators.getStatelessValidator;

/**
 * Generated by {@code RxMicro Annotation Processor}
 */
public final class $$VirtualRequestConstraintValidator implements ConstraintValidator<$$VirtualRequest> {

    private final NotEmptyStringConstraintValidator notEmptyStringConstraintValidator =
            getStatelessValidator(NotEmptyStringConstraintValidator.class);

    private final RequiredConstraintValidator requiredConstraintValidator =
            getStatelessValidator(RequiredConstraintValidator.class);

    private final AssertFalseConstraintValidator assertFalseConstraintValidator =
            getStatelessValidator(AssertFalseConstraintValidator.class);

    private final AssertTrueConstraintValidator assertTrueConstraintValidator =
            getStatelessValidator(AssertTrueConstraintValidator.class);

    private final LowercaseConstraintValidator lowercaseConstraintValidator =
            getStatelessValidator(LowercaseConstraintValidator.class);

    private final SkypeConstraintValidator skypeConstraintValidator =
            getStatelessValidator(SkypeConstraintValidator.class);

    private final URIConstraintValidator uRIConstraintValidator =
            getStatelessValidator(URIConstraintValidator.class);

    private final URLEncodedConstraintValidator uRLEncodedConstraintValidator =
            getStatelessValidator(URLEncodedConstraintValidator.class);

    private final UppercaseConstraintValidator uppercaseConstraintValidator =
            getStatelessValidator(UppercaseConstraintValidator.class);

    private final FutureInstantConstraintValidator futureInstantConstraintValidator =
            getStatelessValidator(FutureInstantConstraintValidator.class);

    private final FutureOrPresentInstantConstraintValidator futureOrPresentInstantConstraintValidator =
            getStatelessValidator(FutureOrPresentInstantConstraintValidator.class);

    private final PastInstantConstraintValidator pastInstantConstraintValidator =
            getStatelessValidator(PastInstantConstraintValidator.class);

    private final PastOrPresentInstantConstraintValidator pastOrPresentInstantConstraintValidator =
            getStatelessValidator(PastOrPresentInstantConstraintValidator.class);

    private final RequiredListConstraintValidator requiredListConstraintValidator =
            getStatelessValidator(RequiredListConstraintValidator.class);

    private final UniqueItemsConstraintValidator uniqueItemsConstraintValidator =
            getStatelessValidator(UniqueItemsConstraintValidator.class);

    private final RequiredAndNotEmptyStringConstraintValidator requiredAndNotEmptyStringConstraintValidator =
            getStatelessValidator(RequiredAndNotEmptyStringConstraintValidator.class);

    private final MaxByteConstraintValidator byteParameterMaxIntMaxByteConstraintValidator =
            new MaxByteConstraintValidator(10L, true);

    private final MaxByteConstraintValidator byteParameterMaxNumberMaxByteConstraintValidator =
            new MaxByteConstraintValidator("10", true);

    private final MinByteConstraintValidator byteParameterMinIntMinByteConstraintValidator =
            new MinByteConstraintValidator(3L, true);

    private final MinByteConstraintValidator byteParameterMinNumberMinByteConstraintValidator =
            new MinByteConstraintValidator("3", true);

    private final MaxShortConstraintValidator shortParameterMaxIntMaxShortConstraintValidator =
            new MaxShortConstraintValidator(10L, true);

    private final MaxShortConstraintValidator shortParameterMaxNumberMaxShortConstraintValidator =
            new MaxShortConstraintValidator("10", true);

    private final MinShortConstraintValidator shortParameterMinIntMinShortConstraintValidator =
            new MinShortConstraintValidator(3L, true);

    private final MinShortConstraintValidator shortParameterMinNumberMinShortConstraintValidator =
            new MinShortConstraintValidator("3", true);

    private final MaxIntConstraintValidator intParameterMaxIntMaxIntConstraintValidator =
            new MaxIntConstraintValidator(10L, true);

    private final MaxIntConstraintValidator intParameterMaxNumberMaxIntConstraintValidator =
            new MaxIntConstraintValidator("10", true);

    private final MinIntConstraintValidator intParameterMinIntMinIntConstraintValidator =
            new MinIntConstraintValidator(3L, true);

    private final MinIntConstraintValidator intParameterMinNumberMinIntConstraintValidator =
            new MinIntConstraintValidator("3", true);

    private final MaxLongConstraintValidator longParameterMaxIntMaxLongConstraintValidator =
            new MaxLongConstraintValidator(10L, true);

    private final MaxLongConstraintValidator longParameterMaxNumberMaxLongConstraintValidator =
            new MaxLongConstraintValidator("10", true);

    private final MinLongConstraintValidator longParameterMinIntMinLongConstraintValidator =
            new MinLongConstraintValidator(3L, true);

    private final MinLongConstraintValidator longParameterMinNumberMinLongConstraintValidator =
            new MinLongConstraintValidator("3", true);

    private final MaxBigIntegerNumberConstraintValidator bigIntParameterMaxNumberMaxBigIntegerNumberConstraintValidator =
            new MaxBigIntegerNumberConstraintValidator("10", true);

    private final MinBigIntegerNumberConstraintValidator bigIntParameterMinNumberMinBigIntegerNumberConstraintValidator =
            new MinBigIntegerNumberConstraintValidator("3", true);

    private final MaxFloatConstraintValidator floatParameterMaxDoubleMaxFloatConstraintValidator =
            new MaxFloatConstraintValidator(10.9);

    private final MaxFloatConstraintValidator floatParameterMaxNumberMaxFloatConstraintValidator =
            new MaxFloatConstraintValidator("10", true);

    private final MinFloatConstraintValidator floatParameterMinDoubleMinFloatConstraintValidator =
            new MinFloatConstraintValidator(3.1);

    private final MinFloatConstraintValidator floatParameterMinNumberMinFloatConstraintValidator =
            new MinFloatConstraintValidator("3", true);

    private final MaxDoubleConstraintValidator doubleParameterMaxDoubleMaxDoubleConstraintValidator =
            new MaxDoubleConstraintValidator(10.9);

    private final MaxDoubleConstraintValidator doubleParameterMaxNumberMaxDoubleConstraintValidator =
            new MaxDoubleConstraintValidator("10", true);

    private final MinDoubleConstraintValidator doubleParameterMinDoubleMinDoubleConstraintValidator =
            new MinDoubleConstraintValidator(3.1);

    private final MinDoubleConstraintValidator doubleParameterMinNumberMinDoubleConstraintValidator =
            new MinDoubleConstraintValidator("3", true);

    private final LatConstraintValidator decimalParameterLatLatConstraintValidator =
            new LatConstraintValidator(LocationAccuracy.ACCURACY_1_METER);

    private final LngConstraintValidator decimalParameterLngLngConstraintValidator =
            new LngConstraintValidator(LocationAccuracy.ACCURACY_1_METER);

    private final MaxBigDecimalNumberConstraintValidator decimalParameterMaxNumberMaxBigDecimalNumberConstraintValidator =
            new MaxBigDecimalNumberConstraintValidator("10.9", true);

    private final MinBigDecimalNumberConstraintValidator decimalParameterMinNumberMinBigDecimalNumberConstraintValidator =
            new MinBigDecimalNumberConstraintValidator("3.1", true);

    private final NumericConstraintValidator decimalParameterNumericNumericConstraintValidator =
            new NumericConstraintValidator(5, 2);

    private final EnumerationCharacterConstraintValidator charParameterEnumerationEnumerationCharacterConstraintValidator =
            new EnumerationCharacterConstraintValidator(List.of("y", "n"));

    private final Base64URLEncodedConstraintValidator stringParameterBase64URLEncodedBase64URLEncodedConstraintValidator =
            new Base64URLEncodedConstraintValidator(Alphabet.URL);

    private final CountryCodeConstraintValidator stringParameterCountryCodeCountryCodeConstraintValidator =
            new CountryCodeConstraintValidator(Format.ISO_3166_1_ALPHA_2);

    private final EmailConstraintValidator stringParameterEmailEmailConstraintValidator =
            new EmailConstraintValidator(false);

    private final EnumerationStringConstraintValidator stringParameterEnumerationEnumerationStringConstraintValidator =
            new EnumerationStringConstraintValidator(List.of("3", "2", "3"));

    private final HostNameConstraintValidator stringParameterHostNameHostNameConstraintValidator =
            new HostNameConstraintValidator(false);

    private final IPConstraintValidator stringParameterIPIPConstraintValidator =
            new IPConstraintValidator(List.of(Version.IP_V4, Version.IP_V6));

    private final LatinAlphabetOnlyConstraintValidator stringParameterLatinAlphabetOnlyLatinAlphabetOnlyConstraintValidator =
            new LatinAlphabetOnlyConstraintValidator(true, true, true, "~!@#$%^&*()_+=-[]{},.;:<>?/\\\"' \t|\r\n\b");

    private final LengthConstraintValidator stringParameterLengthLengthConstraintValidator =
            new LengthConstraintValidator(2);

    private final MaxLengthConstraintValidator stringParameterMaxLengthMaxLengthConstraintValidator =
            new MaxLengthConstraintValidator(2, true);

    private final MinLengthConstraintValidator stringParameterMinLengthMinLengthConstraintValidator =
            new MinLengthConstraintValidator(2, true);

    private final PatternConstraintValidator stringParameterPatternPatternConstraintValidator =
            new PatternConstraintValidator("hello", List.of());

    private final PhoneConstraintValidator stringParameterPhonePhoneConstraintValidator =
            new PhoneConstraintValidator(true, false);

    private final TelegramConstraintValidator stringParameterTelegramTelegramConstraintValidator =
            new TelegramConstraintValidator(true, false);

    private final ViberConstraintValidator stringParameterViberViberConstraintValidator =
            new ViberConstraintValidator(true, false);

    private final WhatsAppConstraintValidator stringParameterWhatsAppWhatsAppConstraintValidator =
            new WhatsAppConstraintValidator(true, false);

    private final TruncatedTimeInstantConstraintValidator instantParameterTruncatedTimeTruncatedTimeInstantConstraintValidator =
            new TruncatedTimeInstantConstraintValidator(Truncated.MILLIS);

    private final SubEnumConstraintValidator colorParameterSubEnumSubEnumConstraintValidator =
            new SubEnumConstraintValidator(Color.class, List.of("RED", "BLUE"), List.of());

    private final MaxSizeConstraintValidator booleanValuesMaxSizeMaxSizeConstraintValidator =
            new MaxSizeConstraintValidator(50, true);

    private final MinSizeConstraintValidator booleanValuesMinSizeMinSizeConstraintValidator =
            new MinSizeConstraintValidator(2, true);

    private final SizeConstraintValidator booleanValuesSizeSizeConstraintValidator =
            new SizeConstraintValidator(12);

    private final MaxByteConstraintValidator byteValuesMaxIntMaxByteConstraintValidator =
            new MaxByteConstraintValidator(10L, true);

    private final MaxSizeConstraintValidator byteValuesMaxSizeMaxSizeConstraintValidator =
            new MaxSizeConstraintValidator(50, true);

    private final MinByteConstraintValidator byteValuesMinIntMinByteConstraintValidator =
            new MinByteConstraintValidator(3L, true);

    private final MinSizeConstraintValidator byteValuesMinSizeMinSizeConstraintValidator =
            new MinSizeConstraintValidator(2, true);

    private final SizeConstraintValidator byteValuesSizeSizeConstraintValidator =
            new SizeConstraintValidator(12);

    private final MaxShortConstraintValidator shortValuesMaxIntMaxShortConstraintValidator =
            new MaxShortConstraintValidator(10L, true);

    private final MaxSizeConstraintValidator shortValuesMaxSizeMaxSizeConstraintValidator =
            new MaxSizeConstraintValidator(50, true);

    private final MinShortConstraintValidator shortValuesMinIntMinShortConstraintValidator =
            new MinShortConstraintValidator(3L, true);

    private final MinSizeConstraintValidator shortValuesMinSizeMinSizeConstraintValidator =
            new MinSizeConstraintValidator(2, true);

    private final SizeConstraintValidator shortValuesSizeSizeConstraintValidator =
            new SizeConstraintValidator(12);

    private final MaxIntConstraintValidator intValuesMaxIntMaxIntConstraintValidator =
            new MaxIntConstraintValidator(10L, true);

    private final MaxSizeConstraintValidator intValuesMaxSizeMaxSizeConstraintValidator =
            new MaxSizeConstraintValidator(50, true);

    private final MinIntConstraintValidator intValuesMinIntMinIntConstraintValidator =
            new MinIntConstraintValidator(3L, true);

    private final MinSizeConstraintValidator intValuesMinSizeMinSizeConstraintValidator =
            new MinSizeConstraintValidator(2, true);

    private final SizeConstraintValidator intValuesSizeSizeConstraintValidator =
            new SizeConstraintValidator(12);

    private final MaxLongConstraintValidator longValuesMaxIntMaxLongConstraintValidator =
            new MaxLongConstraintValidator(10L, true);

    private final MaxSizeConstraintValidator longValuesMaxSizeMaxSizeConstraintValidator =
            new MaxSizeConstraintValidator(50, true);

    private final MinLongConstraintValidator longValuesMinIntMinLongConstraintValidator =
            new MinLongConstraintValidator(3L, true);

    private final MinSizeConstraintValidator longValuesMinSizeMinSizeConstraintValidator =
            new MinSizeConstraintValidator(2, true);

    private final SizeConstraintValidator longValuesSizeSizeConstraintValidator =
            new SizeConstraintValidator(12);

    private final EnumerationCharacterConstraintValidator charValuesEnumerationEnumerationCharacterConstraintValidator =
            new EnumerationCharacterConstraintValidator(List.of("y", "n"));

    private final MaxSizeConstraintValidator charValuesMaxSizeMaxSizeConstraintValidator =
            new MaxSizeConstraintValidator(50, true);

    private final MinSizeConstraintValidator charValuesMinSizeMinSizeConstraintValidator =
            new MinSizeConstraintValidator(2, true);

    private final SizeConstraintValidator charValuesSizeSizeConstraintValidator =
            new SizeConstraintValidator(12);

    private final MaxFloatConstraintValidator floatValuesMaxDoubleMaxFloatConstraintValidator =
            new MaxFloatConstraintValidator(10.9);

    private final MaxSizeConstraintValidator floatValuesMaxSizeMaxSizeConstraintValidator =
            new MaxSizeConstraintValidator(50, true);

    private final MinFloatConstraintValidator floatValuesMinDoubleMinFloatConstraintValidator =
            new MinFloatConstraintValidator(3.1);

    private final MinSizeConstraintValidator floatValuesMinSizeMinSizeConstraintValidator =
            new MinSizeConstraintValidator(2, true);

    private final SizeConstraintValidator floatValuesSizeSizeConstraintValidator =
            new SizeConstraintValidator(12);

    private final MaxDoubleConstraintValidator doubleValuesMaxDoubleMaxDoubleConstraintValidator =
            new MaxDoubleConstraintValidator(10.9);

    private final MaxSizeConstraintValidator doubleValuesMaxSizeMaxSizeConstraintValidator =
            new MaxSizeConstraintValidator(50, true);

    private final MinDoubleConstraintValidator doubleValuesMinDoubleMinDoubleConstraintValidator =
            new MinDoubleConstraintValidator(3.1);

    private final MinSizeConstraintValidator doubleValuesMinSizeMinSizeConstraintValidator =
            new MinSizeConstraintValidator(2, true);

    private final SizeConstraintValidator doubleValuesSizeSizeConstraintValidator =
            new SizeConstraintValidator(12);

    private final LatConstraintValidator decimalsLatLatConstraintValidator =
            new LatConstraintValidator(LocationAccuracy.ACCURACY_1_METER);

    private final LngConstraintValidator decimalsLngLngConstraintValidator =
            new LngConstraintValidator(LocationAccuracy.ACCURACY_1_METER);

    private final MaxBigDecimalNumberConstraintValidator decimalsMaxNumberMaxBigDecimalNumberConstraintValidator =
            new MaxBigDecimalNumberConstraintValidator("10.9", true);

    private final MaxSizeConstraintValidator decimalsMaxSizeMaxSizeConstraintValidator =
            new MaxSizeConstraintValidator(50, true);

    private final MinBigDecimalNumberConstraintValidator decimalsMinNumberMinBigDecimalNumberConstraintValidator =
            new MinBigDecimalNumberConstraintValidator("3.1", true);

    private final MinSizeConstraintValidator decimalsMinSizeMinSizeConstraintValidator =
            new MinSizeConstraintValidator(2, true);

    private final NumericConstraintValidator decimalsNumericNumericConstraintValidator =
            new NumericConstraintValidator(5, 2);

    private final SizeConstraintValidator decimalsSizeSizeConstraintValidator =
            new SizeConstraintValidator(12);

    private final MaxBigIntegerNumberConstraintValidator bigIntegersMaxNumberMaxBigIntegerNumberConstraintValidator =
            new MaxBigIntegerNumberConstraintValidator("10", true);

    private final MaxSizeConstraintValidator bigIntegersMaxSizeMaxSizeConstraintValidator =
            new MaxSizeConstraintValidator(50, true);

    private final MinBigIntegerNumberConstraintValidator bigIntegersMinNumberMinBigIntegerNumberConstraintValidator =
            new MinBigIntegerNumberConstraintValidator("3", true);

    private final MinSizeConstraintValidator bigIntegersMinSizeMinSizeConstraintValidator =
            new MinSizeConstraintValidator(2, true);

    private final SizeConstraintValidator bigIntegersSizeSizeConstraintValidator =
            new SizeConstraintValidator(12);

    private final Base64URLEncodedConstraintValidator stringsBase64URLEncodedBase64URLEncodedConstraintValidator =
            new Base64URLEncodedConstraintValidator(Alphabet.URL);

    private final CountryCodeConstraintValidator stringsCountryCodeCountryCodeConstraintValidator =
            new CountryCodeConstraintValidator(Format.ISO_3166_1_ALPHA_2);

    private final EmailConstraintValidator stringsEmailEmailConstraintValidator =
            new EmailConstraintValidator(false);

    private final EnumerationStringConstraintValidator stringsEnumerationEnumerationStringConstraintValidator =
            new EnumerationStringConstraintValidator(List.of("3", "2", "3"));

    private final HostNameConstraintValidator stringsHostNameHostNameConstraintValidator =
            new HostNameConstraintValidator(false);

    private final IPConstraintValidator stringsIPIPConstraintValidator =
            new IPConstraintValidator(List.of(Version.IP_V4, Version.IP_V6));

    private final LatinAlphabetOnlyConstraintValidator stringsLatinAlphabetOnlyLatinAlphabetOnlyConstraintValidator =
            new LatinAlphabetOnlyConstraintValidator(true, true, true, "~!@#$%^&*()_+=-[]{},.;:<>?/\\\"' \t|\r\n\b");

    private final LengthConstraintValidator stringsLengthLengthConstraintValidator =
            new LengthConstraintValidator(2);

    private final MaxLengthConstraintValidator stringsMaxLengthMaxLengthConstraintValidator =
            new MaxLengthConstraintValidator(2, true);

    private final MaxSizeConstraintValidator stringsMaxSizeMaxSizeConstraintValidator =
            new MaxSizeConstraintValidator(50, true);

    private final MinLengthConstraintValidator stringsMinLengthMinLengthConstraintValidator =
            new MinLengthConstraintValidator(2, true);

    private final MinSizeConstraintValidator stringsMinSizeMinSizeConstraintValidator =
            new MinSizeConstraintValidator(2, true);

    private final PatternConstraintValidator stringsPatternPatternConstraintValidator =
            new PatternConstraintValidator("hello", List.of());

    private final PhoneConstraintValidator stringsPhonePhoneConstraintValidator =
            new PhoneConstraintValidator(true, false);

    private final SizeConstraintValidator stringsSizeSizeConstraintValidator =
            new SizeConstraintValidator(12);

    private final TelegramConstraintValidator stringsTelegramTelegramConstraintValidator =
            new TelegramConstraintValidator(true, false);

    private final ViberConstraintValidator stringsViberViberConstraintValidator =
            new ViberConstraintValidator(true, false);

    private final WhatsAppConstraintValidator stringsWhatsAppWhatsAppConstraintValidator =
            new WhatsAppConstraintValidator(true, false);

    private final MaxSizeConstraintValidator instantsMaxSizeMaxSizeConstraintValidator =
            new MaxSizeConstraintValidator(50, true);

    private final MinSizeConstraintValidator instantsMinSizeMinSizeConstraintValidator =
            new MinSizeConstraintValidator(2, true);

    private final SizeConstraintValidator instantsSizeSizeConstraintValidator =
            new SizeConstraintValidator(12);

    private final TruncatedTimeInstantConstraintValidator instantsTruncatedTimeTruncatedTimeInstantConstraintValidator =
            new TruncatedTimeInstantConstraintValidator(Truncated.MILLIS);

    private final MaxSizeConstraintValidator colorsMaxSizeMaxSizeConstraintValidator =
            new MaxSizeConstraintValidator(50, true);

    private final MinSizeConstraintValidator colorsMinSizeMinSizeConstraintValidator =
            new MinSizeConstraintValidator(2, true);

    private final SizeConstraintValidator colorsSizeSizeConstraintValidator =
            new SizeConstraintValidator(12);

    private final SubEnumConstraintValidator colorsSubEnumSubEnumConstraintValidator =
            new SubEnumConstraintValidator(Color.class, List.of("RED", "BLUE"), List.of());

    private final CountryCodeConstraintValidator countryCodeAlpha2CountryCodeCountryCodeConstraintValidator =
            new CountryCodeConstraintValidator(Format.ISO_3166_1_ALPHA_2);

    private final CountryCodeConstraintValidator countryCodeAlpha3CountryCodeCountryCodeConstraintValidator =
            new CountryCodeConstraintValidator(Format.ISO_3166_1_ALPHA_3);

    private final CountryCodeConstraintValidator countryCodeNumericCountryCodeCountryCodeConstraintValidator =
            new CountryCodeConstraintValidator(Format.ISO_3166_1_NUMERIC);

    private final Base64URLEncodedConstraintValidator base64URLEncodedBaseBase64URLEncodedBase64URLEncodedConstraintValidator =
            new Base64URLEncodedConstraintValidator(Alphabet.BASE);

    private final Base64URLEncodedConstraintValidator base64URLEncodedUrlBase64URLEncodedBase64URLEncodedConstraintValidator =
            new Base64URLEncodedConstraintValidator(Alphabet.URL);

    private final IPConstraintValidator ipIPIPConstraintValidator =
            new IPConstraintValidator(List.of(Version.IP_V4, Version.IP_V6));

    private final IPConstraintValidator ip4IPIPConstraintValidator =
            new IPConstraintValidator(List.of(Version.IP_V4));

    private final IPConstraintValidator ip6IPIPConstraintValidator =
            new IPConstraintValidator(List.of(Version.IP_V6));

    private final LatConstraintValidator lat111kmLatLatConstraintValidator =
            new LatConstraintValidator(LocationAccuracy.ACCURACY_111_KILOMETERS);

    private final LngConstraintValidator lng111kmLngLngConstraintValidator =
            new LngConstraintValidator(LocationAccuracy.ACCURACY_111_KILOMETERS);

    private final LatConstraintValidator lat11kmLatLatConstraintValidator =
            new LatConstraintValidator(LocationAccuracy.ACCURACY_11_KILOMETERS);

    private final LngConstraintValidator lng11kmLngLngConstraintValidator =
            new LngConstraintValidator(LocationAccuracy.ACCURACY_11_KILOMETERS);

    private final LatConstraintValidator lat1kmLatLatConstraintValidator =
            new LatConstraintValidator(LocationAccuracy.ACCURACY_1_KILOMETER);

    private final LngConstraintValidator lng1kmLngLngConstraintValidator =
            new LngConstraintValidator(LocationAccuracy.ACCURACY_1_KILOMETER);

    private final LatConstraintValidator lat111mLatLatConstraintValidator =
            new LatConstraintValidator(LocationAccuracy.ACCURACY_111_METERS);

    private final LngConstraintValidator lng111mLngLngConstraintValidator =
            new LngConstraintValidator(LocationAccuracy.ACCURACY_111_METERS);

    private final LatConstraintValidator lat11mLatLatConstraintValidator =
            new LatConstraintValidator(LocationAccuracy.ACCURACY_11_METERS);

    private final LngConstraintValidator lng11mLngLngConstraintValidator =
            new LngConstraintValidator(LocationAccuracy.ACCURACY_11_METERS);

    private final LatConstraintValidator lat1mLatLatConstraintValidator =
            new LatConstraintValidator(LocationAccuracy.ACCURACY_1_METER);

    private final LngConstraintValidator lng1mLngLngConstraintValidator =
            new LngConstraintValidator(LocationAccuracy.ACCURACY_1_METER);

    private final LatConstraintValidator lat11cmLatLatConstraintValidator =
            new LatConstraintValidator(LocationAccuracy.ACCURACY_11_CENTIMETERS);

    private final LngConstraintValidator lng11cmLngLngConstraintValidator =
            new LngConstraintValidator(LocationAccuracy.ACCURACY_11_CENTIMETERS);

    private final LatConstraintValidator lat1cmLatLatConstraintValidator =
            new LatConstraintValidator(LocationAccuracy.ACCURACY_1_CENTIMETER);

    private final LngConstraintValidator lng1cmLngLngConstraintValidator =
            new LngConstraintValidator(LocationAccuracy.ACCURACY_1_CENTIMETER);

    @Override
    public void validate(final $$VirtualRequest model,
                         final HttpModelType httpModelType,
                         final String name) throws ValidationException {
        notEmptyStringConstraintValidator.validate(model.optionalParameter, HttpModelType.PARAMETER, "optionalParameter");

        requiredConstraintValidator.validate(model.booleanParameter, HttpModelType.PARAMETER, "booleanParameter");
        assertFalseConstraintValidator.validate(model.booleanParameter, HttpModelType.PARAMETER, "booleanParameter");
        assertTrueConstraintValidator.validate(model.booleanParameter, HttpModelType.PARAMETER, "booleanParameter");

        requiredConstraintValidator.validate(model.byteParameter, HttpModelType.PARAMETER, "byteParameter");
        byteParameterMaxIntMaxByteConstraintValidator.validate(model.byteParameter, HttpModelType.PARAMETER, "byteParameter");
        byteParameterMaxNumberMaxByteConstraintValidator.validate(model.byteParameter, HttpModelType.PARAMETER, "byteParameter");
        byteParameterMinIntMinByteConstraintValidator.validate(model.byteParameter, HttpModelType.PARAMETER, "byteParameter");
        byteParameterMinNumberMinByteConstraintValidator.validate(model.byteParameter, HttpModelType.PARAMETER, "byteParameter");

        requiredConstraintValidator.validate(model.shortParameter, HttpModelType.PARAMETER, "shortParameter");
        shortParameterMaxIntMaxShortConstraintValidator.validate(model.shortParameter, HttpModelType.PARAMETER, "shortParameter");
        shortParameterMaxNumberMaxShortConstraintValidator.validate(model.shortParameter, HttpModelType.PARAMETER, "shortParameter");
        shortParameterMinIntMinShortConstraintValidator.validate(model.shortParameter, HttpModelType.PARAMETER, "shortParameter");
        shortParameterMinNumberMinShortConstraintValidator.validate(model.shortParameter, HttpModelType.PARAMETER, "shortParameter");

        requiredConstraintValidator.validate(model.intParameter, HttpModelType.PARAMETER, "intParameter");
        intParameterMaxIntMaxIntConstraintValidator.validate(model.intParameter, HttpModelType.PARAMETER, "intParameter");
        intParameterMaxNumberMaxIntConstraintValidator.validate(model.intParameter, HttpModelType.PARAMETER, "intParameter");
        intParameterMinIntMinIntConstraintValidator.validate(model.intParameter, HttpModelType.PARAMETER, "intParameter");
        intParameterMinNumberMinIntConstraintValidator.validate(model.intParameter, HttpModelType.PARAMETER, "intParameter");

        requiredConstraintValidator.validate(model.longParameter, HttpModelType.PARAMETER, "longParameter");
        longParameterMaxIntMaxLongConstraintValidator.validate(model.longParameter, HttpModelType.PARAMETER, "longParameter");
        longParameterMaxNumberMaxLongConstraintValidator.validate(model.longParameter, HttpModelType.PARAMETER, "longParameter");
        longParameterMinIntMinLongConstraintValidator.validate(model.longParameter, HttpModelType.PARAMETER, "longParameter");
        longParameterMinNumberMinLongConstraintValidator.validate(model.longParameter, HttpModelType.PARAMETER, "longParameter");

        requiredConstraintValidator.validate(model.bigIntParameter, HttpModelType.PARAMETER, "bigIntParameter");
        bigIntParameterMaxNumberMaxBigIntegerNumberConstraintValidator.validate(model.bigIntParameter, HttpModelType.PARAMETER, "bigIntParameter");
        bigIntParameterMinNumberMinBigIntegerNumberConstraintValidator.validate(model.bigIntParameter, HttpModelType.PARAMETER, "bigIntParameter");

        requiredConstraintValidator.validate(model.floatParameter, HttpModelType.PARAMETER, "floatParameter");
        floatParameterMaxDoubleMaxFloatConstraintValidator.validate(model.floatParameter, HttpModelType.PARAMETER, "floatParameter");
        floatParameterMaxNumberMaxFloatConstraintValidator.validate(model.floatParameter, HttpModelType.PARAMETER, "floatParameter");
        floatParameterMinDoubleMinFloatConstraintValidator.validate(model.floatParameter, HttpModelType.PARAMETER, "floatParameter");
        floatParameterMinNumberMinFloatConstraintValidator.validate(model.floatParameter, HttpModelType.PARAMETER, "floatParameter");

        requiredConstraintValidator.validate(model.doubleParameter, HttpModelType.PARAMETER, "doubleParameter");
        doubleParameterMaxDoubleMaxDoubleConstraintValidator.validate(model.doubleParameter, HttpModelType.PARAMETER, "doubleParameter");
        doubleParameterMaxNumberMaxDoubleConstraintValidator.validate(model.doubleParameter, HttpModelType.PARAMETER, "doubleParameter");
        doubleParameterMinDoubleMinDoubleConstraintValidator.validate(model.doubleParameter, HttpModelType.PARAMETER, "doubleParameter");
        doubleParameterMinNumberMinDoubleConstraintValidator.validate(model.doubleParameter, HttpModelType.PARAMETER, "doubleParameter");

        requiredConstraintValidator.validate(model.decimalParameter, HttpModelType.PARAMETER, "decimalParameter");
        decimalParameterLatLatConstraintValidator.validate(model.decimalParameter, HttpModelType.PARAMETER, "decimalParameter");
        decimalParameterLngLngConstraintValidator.validate(model.decimalParameter, HttpModelType.PARAMETER, "decimalParameter");
        decimalParameterMaxNumberMaxBigDecimalNumberConstraintValidator.validate(model.decimalParameter, HttpModelType.PARAMETER, "decimalParameter");
        decimalParameterMinNumberMinBigDecimalNumberConstraintValidator.validate(model.decimalParameter, HttpModelType.PARAMETER, "decimalParameter");
        decimalParameterNumericNumericConstraintValidator.validate(model.decimalParameter, HttpModelType.PARAMETER, "decimalParameter");

        requiredConstraintValidator.validate(model.charParameter, HttpModelType.PARAMETER, "charParameter");
        charParameterEnumerationEnumerationCharacterConstraintValidator.validate(model.charParameter, HttpModelType.PARAMETER, "charParameter");

        requiredConstraintValidator.validate(model.stringParameter, HttpModelType.PARAMETER, "stringParameter");
        stringParameterBase64URLEncodedBase64URLEncodedConstraintValidator.validate(model.stringParameter, HttpModelType.PARAMETER, "stringParameter");
        stringParameterCountryCodeCountryCodeConstraintValidator.validate(model.stringParameter, HttpModelType.PARAMETER, "stringParameter");
        stringParameterEmailEmailConstraintValidator.validate(model.stringParameter, HttpModelType.PARAMETER, "stringParameter");
        stringParameterEnumerationEnumerationStringConstraintValidator.validate(model.stringParameter, HttpModelType.PARAMETER, "stringParameter");
        stringParameterHostNameHostNameConstraintValidator.validate(model.stringParameter, HttpModelType.PARAMETER, "stringParameter");
        stringParameterIPIPConstraintValidator.validate(model.stringParameter, HttpModelType.PARAMETER, "stringParameter");
        stringParameterLatinAlphabetOnlyLatinAlphabetOnlyConstraintValidator.validate(model.stringParameter, HttpModelType.PARAMETER, "stringParameter");
        stringParameterLengthLengthConstraintValidator.validate(model.stringParameter, HttpModelType.PARAMETER, "stringParameter");
        lowercaseConstraintValidator.validate(model.stringParameter, HttpModelType.PARAMETER, "stringParameter");
        stringParameterMaxLengthMaxLengthConstraintValidator.validate(model.stringParameter, HttpModelType.PARAMETER, "stringParameter");
        stringParameterMinLengthMinLengthConstraintValidator.validate(model.stringParameter, HttpModelType.PARAMETER, "stringParameter");
        stringParameterPatternPatternConstraintValidator.validate(model.stringParameter, HttpModelType.PARAMETER, "stringParameter");
        stringParameterPhonePhoneConstraintValidator.validate(model.stringParameter, HttpModelType.PARAMETER, "stringParameter");
        skypeConstraintValidator.validate(model.stringParameter, HttpModelType.PARAMETER, "stringParameter");
        stringParameterTelegramTelegramConstraintValidator.validate(model.stringParameter, HttpModelType.PARAMETER, "stringParameter");
        uRIConstraintValidator.validate(model.stringParameter, HttpModelType.PARAMETER, "stringParameter");
        uRLEncodedConstraintValidator.validate(model.stringParameter, HttpModelType.PARAMETER, "stringParameter");
        uppercaseConstraintValidator.validate(model.stringParameter, HttpModelType.PARAMETER, "stringParameter");
        stringParameterViberViberConstraintValidator.validate(model.stringParameter, HttpModelType.PARAMETER, "stringParameter");
        stringParameterWhatsAppWhatsAppConstraintValidator.validate(model.stringParameter, HttpModelType.PARAMETER, "stringParameter");

        requiredConstraintValidator.validate(model.instantParameter, HttpModelType.PARAMETER, "instantParameter");
        futureInstantConstraintValidator.validate(model.instantParameter, HttpModelType.PARAMETER, "instantParameter");
        futureOrPresentInstantConstraintValidator.validate(model.instantParameter, HttpModelType.PARAMETER, "instantParameter");
        pastInstantConstraintValidator.validate(model.instantParameter, HttpModelType.PARAMETER, "instantParameter");
        pastOrPresentInstantConstraintValidator.validate(model.instantParameter, HttpModelType.PARAMETER, "instantParameter");
        instantParameterTruncatedTimeTruncatedTimeInstantConstraintValidator.validate(model.instantParameter, HttpModelType.PARAMETER, "instantParameter");

        requiredConstraintValidator.validate(model.colorParameter, HttpModelType.PARAMETER, "colorParameter");
        colorParameterSubEnumSubEnumConstraintValidator.validate(model.colorParameter, HttpModelType.PARAMETER, "colorParameter");

        notEmptyStringConstraintValidator.validateList(model.optionalList, HttpModelType.PARAMETER, "optionalList");

        requiredListConstraintValidator.validate(model.booleanValues, HttpModelType.PARAMETER, "booleanValues");
        requiredConstraintValidator.validateList(model.booleanValues, HttpModelType.PARAMETER, "booleanValues");
        assertFalseConstraintValidator.validateList(model.booleanValues, HttpModelType.PARAMETER, "booleanValues");
        assertTrueConstraintValidator.validateList(model.booleanValues, HttpModelType.PARAMETER, "booleanValues");
        booleanValuesMaxSizeMaxSizeConstraintValidator.validate(model.booleanValues, HttpModelType.PARAMETER, "booleanValues");
        booleanValuesMinSizeMinSizeConstraintValidator.validate(model.booleanValues, HttpModelType.PARAMETER, "booleanValues");
        booleanValuesSizeSizeConstraintValidator.validate(model.booleanValues, HttpModelType.PARAMETER, "booleanValues");
        uniqueItemsConstraintValidator.validate(model.booleanValues, HttpModelType.PARAMETER, "booleanValues");

        requiredListConstraintValidator.validate(model.byteValues, HttpModelType.PARAMETER, "byteValues");
        requiredConstraintValidator.validateList(model.byteValues, HttpModelType.PARAMETER, "byteValues");
        byteValuesMaxIntMaxByteConstraintValidator.validateList(model.byteValues, HttpModelType.PARAMETER, "byteValues");
        byteValuesMaxSizeMaxSizeConstraintValidator.validate(model.byteValues, HttpModelType.PARAMETER, "byteValues");
        byteValuesMinIntMinByteConstraintValidator.validateList(model.byteValues, HttpModelType.PARAMETER, "byteValues");
        byteValuesMinSizeMinSizeConstraintValidator.validate(model.byteValues, HttpModelType.PARAMETER, "byteValues");
        byteValuesSizeSizeConstraintValidator.validate(model.byteValues, HttpModelType.PARAMETER, "byteValues");
        uniqueItemsConstraintValidator.validate(model.byteValues, HttpModelType.PARAMETER, "byteValues");

        requiredListConstraintValidator.validate(model.shortValues, HttpModelType.PARAMETER, "shortValues");
        requiredConstraintValidator.validateList(model.shortValues, HttpModelType.PARAMETER, "shortValues");
        shortValuesMaxIntMaxShortConstraintValidator.validateList(model.shortValues, HttpModelType.PARAMETER, "shortValues");
        shortValuesMaxSizeMaxSizeConstraintValidator.validate(model.shortValues, HttpModelType.PARAMETER, "shortValues");
        shortValuesMinIntMinShortConstraintValidator.validateList(model.shortValues, HttpModelType.PARAMETER, "shortValues");
        shortValuesMinSizeMinSizeConstraintValidator.validate(model.shortValues, HttpModelType.PARAMETER, "shortValues");
        shortValuesSizeSizeConstraintValidator.validate(model.shortValues, HttpModelType.PARAMETER, "shortValues");
        uniqueItemsConstraintValidator.validate(model.shortValues, HttpModelType.PARAMETER, "shortValues");

        requiredListConstraintValidator.validate(model.intValues, HttpModelType.PARAMETER, "intValues");
        requiredConstraintValidator.validateList(model.intValues, HttpModelType.PARAMETER, "intValues");
        intValuesMaxIntMaxIntConstraintValidator.validateList(model.intValues, HttpModelType.PARAMETER, "intValues");
        intValuesMaxSizeMaxSizeConstraintValidator.validate(model.intValues, HttpModelType.PARAMETER, "intValues");
        intValuesMinIntMinIntConstraintValidator.validateList(model.intValues, HttpModelType.PARAMETER, "intValues");
        intValuesMinSizeMinSizeConstraintValidator.validate(model.intValues, HttpModelType.PARAMETER, "intValues");
        intValuesSizeSizeConstraintValidator.validate(model.intValues, HttpModelType.PARAMETER, "intValues");
        uniqueItemsConstraintValidator.validate(model.intValues, HttpModelType.PARAMETER, "intValues");

        requiredListConstraintValidator.validate(model.longValues, HttpModelType.PARAMETER, "longValues");
        requiredConstraintValidator.validateList(model.longValues, HttpModelType.PARAMETER, "longValues");
        longValuesMaxIntMaxLongConstraintValidator.validateList(model.longValues, HttpModelType.PARAMETER, "longValues");
        longValuesMaxSizeMaxSizeConstraintValidator.validate(model.longValues, HttpModelType.PARAMETER, "longValues");
        longValuesMinIntMinLongConstraintValidator.validateList(model.longValues, HttpModelType.PARAMETER, "longValues");
        longValuesMinSizeMinSizeConstraintValidator.validate(model.longValues, HttpModelType.PARAMETER, "longValues");
        longValuesSizeSizeConstraintValidator.validate(model.longValues, HttpModelType.PARAMETER, "longValues");
        uniqueItemsConstraintValidator.validate(model.longValues, HttpModelType.PARAMETER, "longValues");

        requiredListConstraintValidator.validate(model.charValues, HttpModelType.PARAMETER, "charValues");
        requiredConstraintValidator.validateList(model.charValues, HttpModelType.PARAMETER, "charValues");
        charValuesEnumerationEnumerationCharacterConstraintValidator.validateList(model.charValues, HttpModelType.PARAMETER, "charValues");
        charValuesMaxSizeMaxSizeConstraintValidator.validate(model.charValues, HttpModelType.PARAMETER, "charValues");
        charValuesMinSizeMinSizeConstraintValidator.validate(model.charValues, HttpModelType.PARAMETER, "charValues");
        charValuesSizeSizeConstraintValidator.validate(model.charValues, HttpModelType.PARAMETER, "charValues");
        uniqueItemsConstraintValidator.validate(model.charValues, HttpModelType.PARAMETER, "charValues");

        requiredListConstraintValidator.validate(model.floatValues, HttpModelType.PARAMETER, "floatValues");
        requiredConstraintValidator.validateList(model.floatValues, HttpModelType.PARAMETER, "floatValues");
        floatValuesMaxDoubleMaxFloatConstraintValidator.validateList(model.floatValues, HttpModelType.PARAMETER, "floatValues");
        floatValuesMaxSizeMaxSizeConstraintValidator.validate(model.floatValues, HttpModelType.PARAMETER, "floatValues");
        floatValuesMinDoubleMinFloatConstraintValidator.validateList(model.floatValues, HttpModelType.PARAMETER, "floatValues");
        floatValuesMinSizeMinSizeConstraintValidator.validate(model.floatValues, HttpModelType.PARAMETER, "floatValues");
        floatValuesSizeSizeConstraintValidator.validate(model.floatValues, HttpModelType.PARAMETER, "floatValues");
        uniqueItemsConstraintValidator.validate(model.floatValues, HttpModelType.PARAMETER, "floatValues");

        requiredListConstraintValidator.validate(model.doubleValues, HttpModelType.PARAMETER, "doubleValues");
        requiredConstraintValidator.validateList(model.doubleValues, HttpModelType.PARAMETER, "doubleValues");
        doubleValuesMaxDoubleMaxDoubleConstraintValidator.validateList(model.doubleValues, HttpModelType.PARAMETER, "doubleValues");
        doubleValuesMaxSizeMaxSizeConstraintValidator.validate(model.doubleValues, HttpModelType.PARAMETER, "doubleValues");
        doubleValuesMinDoubleMinDoubleConstraintValidator.validateList(model.doubleValues, HttpModelType.PARAMETER, "doubleValues");
        doubleValuesMinSizeMinSizeConstraintValidator.validate(model.doubleValues, HttpModelType.PARAMETER, "doubleValues");
        doubleValuesSizeSizeConstraintValidator.validate(model.doubleValues, HttpModelType.PARAMETER, "doubleValues");
        uniqueItemsConstraintValidator.validate(model.doubleValues, HttpModelType.PARAMETER, "doubleValues");

        requiredListConstraintValidator.validate(model.decimals, HttpModelType.PARAMETER, "decimals");
        requiredConstraintValidator.validateList(model.decimals, HttpModelType.PARAMETER, "decimals");
        decimalsLatLatConstraintValidator.validateList(model.decimals, HttpModelType.PARAMETER, "decimals");
        decimalsLngLngConstraintValidator.validateList(model.decimals, HttpModelType.PARAMETER, "decimals");
        decimalsMaxNumberMaxBigDecimalNumberConstraintValidator.validateList(model.decimals, HttpModelType.PARAMETER, "decimals");
        decimalsMaxSizeMaxSizeConstraintValidator.validate(model.decimals, HttpModelType.PARAMETER, "decimals");
        decimalsMinNumberMinBigDecimalNumberConstraintValidator.validateList(model.decimals, HttpModelType.PARAMETER, "decimals");
        decimalsMinSizeMinSizeConstraintValidator.validate(model.decimals, HttpModelType.PARAMETER, "decimals");
        decimalsNumericNumericConstraintValidator.validateList(model.decimals, HttpModelType.PARAMETER, "decimals");
        decimalsSizeSizeConstraintValidator.validate(model.decimals, HttpModelType.PARAMETER, "decimals");
        uniqueItemsConstraintValidator.validate(model.decimals, HttpModelType.PARAMETER, "decimals");

        requiredListConstraintValidator.validate(model.bigIntegers, HttpModelType.PARAMETER, "bigIntegers");
        requiredConstraintValidator.validateList(model.bigIntegers, HttpModelType.PARAMETER, "bigIntegers");
        bigIntegersMaxNumberMaxBigIntegerNumberConstraintValidator.validateList(model.bigIntegers, HttpModelType.PARAMETER, "bigIntegers");
        bigIntegersMaxSizeMaxSizeConstraintValidator.validate(model.bigIntegers, HttpModelType.PARAMETER, "bigIntegers");
        bigIntegersMinNumberMinBigIntegerNumberConstraintValidator.validateList(model.bigIntegers, HttpModelType.PARAMETER, "bigIntegers");
        bigIntegersMinSizeMinSizeConstraintValidator.validate(model.bigIntegers, HttpModelType.PARAMETER, "bigIntegers");
        bigIntegersSizeSizeConstraintValidator.validate(model.bigIntegers, HttpModelType.PARAMETER, "bigIntegers");
        uniqueItemsConstraintValidator.validate(model.bigIntegers, HttpModelType.PARAMETER, "bigIntegers");

        requiredListConstraintValidator.validate(model.strings, HttpModelType.PARAMETER, "strings");
        requiredConstraintValidator.validateList(model.strings, HttpModelType.PARAMETER, "strings");
        stringsBase64URLEncodedBase64URLEncodedConstraintValidator.validateList(model.strings, HttpModelType.PARAMETER, "strings");
        stringsCountryCodeCountryCodeConstraintValidator.validateList(model.strings, HttpModelType.PARAMETER, "strings");
        stringsEmailEmailConstraintValidator.validateList(model.strings, HttpModelType.PARAMETER, "strings");
        stringsEnumerationEnumerationStringConstraintValidator.validateList(model.strings, HttpModelType.PARAMETER, "strings");
        stringsHostNameHostNameConstraintValidator.validateList(model.strings, HttpModelType.PARAMETER, "strings");
        stringsIPIPConstraintValidator.validateList(model.strings, HttpModelType.PARAMETER, "strings");
        stringsLatinAlphabetOnlyLatinAlphabetOnlyConstraintValidator.validateList(model.strings, HttpModelType.PARAMETER, "strings");
        stringsLengthLengthConstraintValidator.validateList(model.strings, HttpModelType.PARAMETER, "strings");
        lowercaseConstraintValidator.validateList(model.strings, HttpModelType.PARAMETER, "strings");
        stringsMaxLengthMaxLengthConstraintValidator.validateList(model.strings, HttpModelType.PARAMETER, "strings");
        stringsMaxSizeMaxSizeConstraintValidator.validate(model.strings, HttpModelType.PARAMETER, "strings");
        stringsMinLengthMinLengthConstraintValidator.validateList(model.strings, HttpModelType.PARAMETER, "strings");
        stringsMinSizeMinSizeConstraintValidator.validate(model.strings, HttpModelType.PARAMETER, "strings");
        stringsPatternPatternConstraintValidator.validateList(model.strings, HttpModelType.PARAMETER, "strings");
        stringsPhonePhoneConstraintValidator.validateList(model.strings, HttpModelType.PARAMETER, "strings");
        stringsSizeSizeConstraintValidator.validate(model.strings, HttpModelType.PARAMETER, "strings");
        skypeConstraintValidator.validateList(model.strings, HttpModelType.PARAMETER, "strings");
        stringsTelegramTelegramConstraintValidator.validateList(model.strings, HttpModelType.PARAMETER, "strings");
        uRIConstraintValidator.validateList(model.strings, HttpModelType.PARAMETER, "strings");
        uRLEncodedConstraintValidator.validateList(model.strings, HttpModelType.PARAMETER, "strings");
        uniqueItemsConstraintValidator.validate(model.strings, HttpModelType.PARAMETER, "strings");
        uppercaseConstraintValidator.validateList(model.strings, HttpModelType.PARAMETER, "strings");
        stringsViberViberConstraintValidator.validateList(model.strings, HttpModelType.PARAMETER, "strings");
        stringsWhatsAppWhatsAppConstraintValidator.validateList(model.strings, HttpModelType.PARAMETER, "strings");

        requiredListConstraintValidator.validate(model.instants, HttpModelType.PARAMETER, "instants");
        requiredConstraintValidator.validateList(model.instants, HttpModelType.PARAMETER, "instants");
        futureInstantConstraintValidator.validateList(model.instants, HttpModelType.PARAMETER, "instants");
        futureOrPresentInstantConstraintValidator.validateList(model.instants, HttpModelType.PARAMETER, "instants");
        instantsMaxSizeMaxSizeConstraintValidator.validate(model.instants, HttpModelType.PARAMETER, "instants");
        instantsMinSizeMinSizeConstraintValidator.validate(model.instants, HttpModelType.PARAMETER, "instants");
        pastInstantConstraintValidator.validateList(model.instants, HttpModelType.PARAMETER, "instants");
        pastOrPresentInstantConstraintValidator.validateList(model.instants, HttpModelType.PARAMETER, "instants");
        instantsSizeSizeConstraintValidator.validate(model.instants, HttpModelType.PARAMETER, "instants");
        instantsTruncatedTimeTruncatedTimeInstantConstraintValidator.validateList(model.instants, HttpModelType.PARAMETER, "instants");
        uniqueItemsConstraintValidator.validate(model.instants, HttpModelType.PARAMETER, "instants");

        requiredListConstraintValidator.validate(model.colors, HttpModelType.PARAMETER, "colors");
        requiredConstraintValidator.validateList(model.colors, HttpModelType.PARAMETER, "colors");
        colorsMaxSizeMaxSizeConstraintValidator.validate(model.colors, HttpModelType.PARAMETER, "colors");
        colorsMinSizeMinSizeConstraintValidator.validate(model.colors, HttpModelType.PARAMETER, "colors");
        colorsSizeSizeConstraintValidator.validate(model.colors, HttpModelType.PARAMETER, "colors");
        colorsSubEnumSubEnumConstraintValidator.validateList(model.colors, HttpModelType.PARAMETER, "colors");
        uniqueItemsConstraintValidator.validate(model.colors, HttpModelType.PARAMETER, "colors");

        requiredAndNotEmptyStringConstraintValidator.validate(model.countryCodeAlpha2, HttpModelType.PARAMETER, "countryCodeAlpha2");
        countryCodeAlpha2CountryCodeCountryCodeConstraintValidator.validate(model.countryCodeAlpha2, HttpModelType.PARAMETER, "countryCodeAlpha2");

        requiredAndNotEmptyStringConstraintValidator.validate(model.countryCodeAlpha3, HttpModelType.PARAMETER, "countryCodeAlpha3");
        countryCodeAlpha3CountryCodeCountryCodeConstraintValidator.validate(model.countryCodeAlpha3, HttpModelType.PARAMETER, "countryCodeAlpha3");

        requiredAndNotEmptyStringConstraintValidator.validate(model.countryCodeNumeric, HttpModelType.PARAMETER, "countryCodeNumeric");
        countryCodeNumericCountryCodeCountryCodeConstraintValidator.validate(model.countryCodeNumeric, HttpModelType.PARAMETER, "countryCodeNumeric");

        requiredAndNotEmptyStringConstraintValidator.validate(model.base64URLEncodedBase, HttpModelType.PARAMETER, "base64URLEncodedBase");
        base64URLEncodedBaseBase64URLEncodedBase64URLEncodedConstraintValidator.validate(model.base64URLEncodedBase, HttpModelType.PARAMETER, "base64URLEncodedBase");

        requiredAndNotEmptyStringConstraintValidator.validate(model.base64URLEncodedUrl, HttpModelType.PARAMETER, "base64URLEncodedUrl");
        base64URLEncodedUrlBase64URLEncodedBase64URLEncodedConstraintValidator.validate(model.base64URLEncodedUrl, HttpModelType.PARAMETER, "base64URLEncodedUrl");

        requiredAndNotEmptyStringConstraintValidator.validate(model.ip, HttpModelType.PARAMETER, "ip");
        ipIPIPConstraintValidator.validate(model.ip, HttpModelType.PARAMETER, "ip");

        requiredAndNotEmptyStringConstraintValidator.validate(model.ip4, HttpModelType.PARAMETER, "ip4");
        ip4IPIPConstraintValidator.validate(model.ip4, HttpModelType.PARAMETER, "ip4");

        requiredAndNotEmptyStringConstraintValidator.validate(model.ip6, HttpModelType.PARAMETER, "ip6");
        ip6IPIPConstraintValidator.validate(model.ip6, HttpModelType.PARAMETER, "ip6");

        requiredConstraintValidator.validate(model.lat111km, HttpModelType.PARAMETER, "lat111km");
        lat111kmLatLatConstraintValidator.validate(model.lat111km, HttpModelType.PARAMETER, "lat111km");

        requiredConstraintValidator.validate(model.lng111km, HttpModelType.PARAMETER, "lng111km");
        lng111kmLngLngConstraintValidator.validate(model.lng111km, HttpModelType.PARAMETER, "lng111km");

        requiredConstraintValidator.validate(model.lat11km, HttpModelType.PARAMETER, "lat11km");
        lat11kmLatLatConstraintValidator.validate(model.lat11km, HttpModelType.PARAMETER, "lat11km");

        requiredConstraintValidator.validate(model.lng11km, HttpModelType.PARAMETER, "lng11km");
        lng11kmLngLngConstraintValidator.validate(model.lng11km, HttpModelType.PARAMETER, "lng11km");

        requiredConstraintValidator.validate(model.lat1km, HttpModelType.PARAMETER, "lat1km");
        lat1kmLatLatConstraintValidator.validate(model.lat1km, HttpModelType.PARAMETER, "lat1km");

        requiredConstraintValidator.validate(model.lng1km, HttpModelType.PARAMETER, "lng1km");
        lng1kmLngLngConstraintValidator.validate(model.lng1km, HttpModelType.PARAMETER, "lng1km");

        requiredConstraintValidator.validate(model.lat111m, HttpModelType.PARAMETER, "lat111m");
        lat111mLatLatConstraintValidator.validate(model.lat111m, HttpModelType.PARAMETER, "lat111m");

        requiredConstraintValidator.validate(model.lng111m, HttpModelType.PARAMETER, "lng111m");
        lng111mLngLngConstraintValidator.validate(model.lng111m, HttpModelType.PARAMETER, "lng111m");

        requiredConstraintValidator.validate(model.lat11m, HttpModelType.PARAMETER, "lat11m");
        lat11mLatLatConstraintValidator.validate(model.lat11m, HttpModelType.PARAMETER, "lat11m");

        requiredConstraintValidator.validate(model.lng11m, HttpModelType.PARAMETER, "lng11m");
        lng11mLngLngConstraintValidator.validate(model.lng11m, HttpModelType.PARAMETER, "lng11m");

        requiredConstraintValidator.validate(model.lat1m, HttpModelType.PARAMETER, "lat1m");
        lat1mLatLatConstraintValidator.validate(model.lat1m, HttpModelType.PARAMETER, "lat1m");

        requiredConstraintValidator.validate(model.lng1m, HttpModelType.PARAMETER, "lng1m");
        lng1mLngLngConstraintValidator.validate(model.lng1m, HttpModelType.PARAMETER, "lng1m");

        requiredConstraintValidator.validate(model.lat11cm, HttpModelType.PARAMETER, "lat11cm");
        lat11cmLatLatConstraintValidator.validate(model.lat11cm, HttpModelType.PARAMETER, "lat11cm");

        requiredConstraintValidator.validate(model.lng11cm, HttpModelType.PARAMETER, "lng11cm");
        lng11cmLngLngConstraintValidator.validate(model.lng11cm, HttpModelType.PARAMETER, "lng11cm");

        requiredConstraintValidator.validate(model.lat1cm, HttpModelType.PARAMETER, "lat1cm");
        lat1cmLatLatConstraintValidator.validate(model.lat1cm, HttpModelType.PARAMETER, "lat1cm");

        requiredConstraintValidator.validate(model.lng1cm, HttpModelType.PARAMETER, "lng1cm");
        lng1cmLngLngConstraintValidator.validate(model.lng1cm, HttpModelType.PARAMETER, "lng1cm");
    }
}
