package io.rxmicro.examples.rest.controller.model.fields.internals.direct;

import io.rxmicro.rest.server.detail.component.ModelWriter;
import io.rxmicro.rest.server.detail.model.HttpResponse;

/**
 * Generated by rxmicro annotation processor
 *
 * @link http://rxmicro.io
 */
public final class $$ResponseModelWriter extends ModelWriter<Response> {

    public $$ResponseModelWriter(final boolean humanReadableOutput) {
        //do nothing
    }

    @Override
    public void write(final Response model,
                      final HttpResponse response) {
        response.setVersion(model.version);
        response.setOrAddHeaders(model.headers);
        response.setStatus(model.status);
        response.setContent(model.body);
    }
}
