package io.rxmicro.examples.rest.controller.notfound;

/**
 * Generated by rxmicro annotation processor
 *
 * @link https://rxmicro.io
 */
public final class $$VirtualNotFoundRequest2 {

    // Parameters
    Boolean found;

}
