package rxmicro;

import io.rxmicro.examples.validation.client.all.types.$$RESTClient1;
import io.rxmicro.examples.validation.client.all.types.$$RESTClient2;
import io.rxmicro.examples.validation.client.all.types.RESTClient1;
import io.rxmicro.examples.validation.client.all.types.RESTClient2;
import io.rxmicro.http.client.HttpClientConfig;
import io.rxmicro.rest.client.RestClientFactory;

import static io.rxmicro.rest.client.detail.RestClientImplFactory.createRestClient;

/**
 * Generated by rxmicro annotation processor
 */
public final class $$RestClientFactoryImpl extends RestClientFactory {

    static {
        $$EnvironmentCustomizer.customize();
    }

    public $$RestClientFactoryImpl() {
        register(RESTClient1.class, () -> createRestClient(
                "http-client",
                HttpClientConfig.class,
                RESTClient1.class,
                $$RESTClient1::new)
        );
        register(RESTClient2.class, () -> createRestClient(
                "http-client",
                HttpClientConfig.class,
                RESTClient2.class,
                $$RESTClient2::new)
        );
    }
}
