package io.rxmicro.examples.validation.client.all.types;

/**
 * Generated by rxmicro annotation processor
 *
 * @link https://rxmicro.io
 */
public final class $$VirtualREST2Request4 {

    // Parameters
    final String email;

    $$VirtualREST2Request4(final String email) {
        this.email = email;
    }
}
