package io.rxmicro.examples.validation.client.all.types;

/**
 * Generated by rxmicro annotation processor
 */
public final class $$VirtualREST1Request5 {

    // Parameters
    final String email;

    $$VirtualREST1Request5(final String email) {
        this.email = email;
    }
}
