package io.rxmicro.examples.cdi.basic;

import io.rxmicro.cdi.detail.BeanSupplier;

/**
 * Generated by {@code RxMicro Annotation Processor}
 */
public final class $$BusinessServiceImplBeanSupplier extends BeanSupplier<BusinessServiceImpl> {

    @Override
    public BusinessServiceImpl get() {
        return new BusinessServiceImpl();
    }
}
