package io.rxmicro.examples.rest.client.params.model;

import io.rxmicro.rest.client.detail.ClientModelReader;
import io.rxmicro.rest.client.detail.HttpResponse;

/**
 * Generated by {@code RxMicro Annotation Processor}
 */
public final class $$ComplexResponseClientModelReader extends ClientModelReader<ComplexResponse> {

    private final $$ComplexResponseModelFromJsonConverter complexResponseModelFromJsonConverter =
            new $$ComplexResponseModelFromJsonConverter();

    @Override
    public ComplexResponse readSingle(final HttpResponse response) {
        return complexResponseModelFromJsonConverter.fromJsonObject(response.getBody());
    }
}
