package io.rxmicro.examples.rest.client.params.model;

import io.rxmicro.rest.client.detail.QueryBuilder;
import io.rxmicro.rest.client.detail.RequestModelExtractor;

/**
 * Generated by rxmicro annotation processor
 *
 * @link http://rxmicro.io
 */
public final class $$RequestRequestModelExtractor extends RequestModelExtractor<Request> {

    @Override
    public void extract(final Request model,
                        final QueryBuilder queryBuilder) {
        queryBuilder.add("endpoint_version", model.endpointVersion);
        queryBuilder.add("use-Proxy", model.useProxy);
    }
}
