package io.rxmicro.examples.validation.server.required;

import io.rxmicro.examples.validation.server.required.model.$$NotStringModelConstraintValidator;
import io.rxmicro.examples.validation.server.required.model.$$NotStringModelModelReader;
import io.rxmicro.examples.validation.server.required.model.$$PrimitiveStringListModelConstraintValidator;
import io.rxmicro.examples.validation.server.required.model.$$PrimitiveStringListModelModelReader;
import io.rxmicro.examples.validation.server.required.model.$$PrimitiveStringModelConstraintValidator;
import io.rxmicro.examples.validation.server.required.model.$$PrimitiveStringModelModelReader;
import io.rxmicro.examples.validation.server.required.model.$$StringModelWithRequiredAndNotEmptyValidatorsOnlyConstraintValidator;
import io.rxmicro.examples.validation.server.required.model.$$StringModelWithRequiredAndNotEmptyValidatorsOnlyModelReader;
import io.rxmicro.examples.validation.server.required.model.$$StringModelWithRequiredNonNullValidatorsOnlyConstraintValidator;
import io.rxmicro.examples.validation.server.required.model.$$StringModelWithRequiredNonNullValidatorsOnlyModelReader;
import io.rxmicro.examples.validation.server.required.model.NotStringModel;
import io.rxmicro.examples.validation.server.required.model.PrimitiveStringListModel;
import io.rxmicro.examples.validation.server.required.model.PrimitiveStringModel;
import io.rxmicro.examples.validation.server.required.model.StringModelWithRequiredAndNotEmptyValidatorsOnly;
import io.rxmicro.examples.validation.server.required.model.StringModelWithRequiredNonNullValidatorsOnly;
import io.rxmicro.http.HttpHeaders;
import io.rxmicro.rest.model.PathVariableMapping;
import io.rxmicro.rest.server.detail.component.AbstractRestController;
import io.rxmicro.rest.server.detail.component.RestControllerRegistrar;
import io.rxmicro.rest.server.detail.model.HttpRequest;
import io.rxmicro.rest.server.detail.model.HttpResponse;
import io.rxmicro.rest.server.detail.model.Registration;
import io.rxmicro.rest.server.detail.model.mapping.ExactUrlRequestMappingRule;

import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;

/**
 * Generated by {@code RxMicro Annotation Processor}
 */
public final class $$MicroService extends AbstractRestController {

    private MicroService restController;

    private $$NotStringModelModelReader notStringModelModelReader;

    private $$PrimitiveStringModelModelReader primitiveStringModelModelReader;

    private $$PrimitiveStringListModelModelReader primitiveStringListModelModelReader;

    private $$StringModelWithRequiredNonNullValidatorsOnlyModelReader stringModelWithRequiredNonNullValidatorsOnlyModelReader;

    private $$StringModelWithRequiredAndNotEmptyValidatorsOnlyModelReader stringModelWithRequiredAndNotEmptyValidatorsOnlyModelReader;

    private $$NotStringModelConstraintValidator notStringModelConstraintValidator;

    private $$PrimitiveStringModelConstraintValidator primitiveStringModelConstraintValidator;

    private $$PrimitiveStringListModelConstraintValidator primitiveStringListModelConstraintValidator;

    private $$StringModelWithRequiredNonNullValidatorsOnlyConstraintValidator stringModelWithRequiredNonNullValidatorsOnlyConstraintValidator;

    private $$StringModelWithRequiredAndNotEmptyValidatorsOnlyConstraintValidator stringModelWithRequiredAndNotEmptyValidatorsOnlyConstraintValidator;

    @Override
    protected void postConstruct() {
        restController = new MicroService();
        notStringModelModelReader = new $$NotStringModelModelReader();
        primitiveStringModelModelReader = new $$PrimitiveStringModelModelReader();
        primitiveStringListModelModelReader = new $$PrimitiveStringListModelModelReader();
        stringModelWithRequiredNonNullValidatorsOnlyModelReader = new $$StringModelWithRequiredNonNullValidatorsOnlyModelReader();
        stringModelWithRequiredAndNotEmptyValidatorsOnlyModelReader = new $$StringModelWithRequiredAndNotEmptyValidatorsOnlyModelReader();
        notStringModelConstraintValidator = new $$NotStringModelConstraintValidator();
        primitiveStringModelConstraintValidator = new $$PrimitiveStringModelConstraintValidator();
        primitiveStringListModelConstraintValidator = new $$PrimitiveStringListModelConstraintValidator();
        stringModelWithRequiredNonNullValidatorsOnlyConstraintValidator = new $$StringModelWithRequiredNonNullValidatorsOnlyConstraintValidator();
        stringModelWithRequiredAndNotEmptyValidatorsOnlyConstraintValidator = new $$StringModelWithRequiredAndNotEmptyValidatorsOnlyConstraintValidator();
    }

    @Override
    public Class<?> getRestControllerClass() {
        return MicroService.class;
    }

    @Override
    public void register(final RestControllerRegistrar registrar) {
        registrar.register(
                this,
                new Registration(
                        "/",
                        "test1(io.rxmicro.examples.validation.server.required.model.NotStringModel)",
                        this::test1,
                        false,
                        new ExactUrlRequestMappingRule(
                                "GET",
                                "/test1",
                                false
                        )
                ),
                new Registration(
                        "/",
                        "test2(io.rxmicro.examples.validation.server.required.model.PrimitiveStringModel)",
                        this::test2,
                        false,
                        new ExactUrlRequestMappingRule(
                                "GET",
                                "/test2",
                                false
                        )
                ),
                new Registration(
                        "/",
                        "test3(io.rxmicro.examples.validation.server.required.model.PrimitiveStringListModel)",
                        this::test3,
                        false,
                        new ExactUrlRequestMappingRule(
                                "GET",
                                "/test3",
                                false
                        )
                ),
                new Registration(
                        "/",
                        "test4(io.rxmicro.examples.validation.server.required.model.StringModelWithRequiredNonNullValidatorsOnly)",
                        this::test4,
                        false,
                        new ExactUrlRequestMappingRule(
                                "GET",
                                "/test4",
                                false
                        )
                ),
                new Registration(
                        "/",
                        "test5(io.rxmicro.examples.validation.server.required.model.StringModelWithRequiredAndNotEmptyValidatorsOnly)",
                        this::test5,
                        false,
                        new ExactUrlRequestMappingRule(
                                "GET",
                                "/test5",
                                false
                        )
                )
        );
    }

    private CompletionStage<HttpResponse> test1(final PathVariableMapping pathVariableMapping,
                                                final HttpRequest request) {
        final NotStringModel req = notStringModelModelReader.read(pathVariableMapping, request, request.isContentPresent());
        notStringModelConstraintValidator.validate(req);
        final HttpHeaders headers = HttpHeaders.of();
        restController.test1(req);
        return CompletableFuture.completedStage(buildResponse(200, headers));
    }

    private CompletionStage<HttpResponse> test2(final PathVariableMapping pathVariableMapping,
                                                final HttpRequest request) {
        final PrimitiveStringModel req = primitiveStringModelModelReader.read(pathVariableMapping, request, request.isContentPresent());
        primitiveStringModelConstraintValidator.validate(req);
        final HttpHeaders headers = HttpHeaders.of();
        restController.test2(req);
        return CompletableFuture.completedStage(buildResponse(200, headers));
    }

    private CompletionStage<HttpResponse> test3(final PathVariableMapping pathVariableMapping,
                                                final HttpRequest request) {
        final PrimitiveStringListModel req = primitiveStringListModelModelReader.read(pathVariableMapping, request, request.isContentPresent());
        primitiveStringListModelConstraintValidator.validate(req);
        final HttpHeaders headers = HttpHeaders.of();
        restController.test3(req);
        return CompletableFuture.completedStage(buildResponse(200, headers));
    }

    private CompletionStage<HttpResponse> test4(final PathVariableMapping pathVariableMapping,
                                                final HttpRequest request) {
        final StringModelWithRequiredNonNullValidatorsOnly req = stringModelWithRequiredNonNullValidatorsOnlyModelReader.read(pathVariableMapping, request, request.isContentPresent());
        stringModelWithRequiredNonNullValidatorsOnlyConstraintValidator.validate(req);
        final HttpHeaders headers = HttpHeaders.of();
        restController.test4(req);
        return CompletableFuture.completedStage(buildResponse(200, headers));
    }

    private CompletionStage<HttpResponse> test5(final PathVariableMapping pathVariableMapping,
                                                final HttpRequest request) {
        final StringModelWithRequiredAndNotEmptyValidatorsOnly req = stringModelWithRequiredAndNotEmptyValidatorsOnlyModelReader.read(pathVariableMapping, request, request.isContentPresent());
        stringModelWithRequiredAndNotEmptyValidatorsOnlyConstraintValidator.validate(req);
        final HttpHeaders headers = HttpHeaders.of();
        restController.test5(req);
        return CompletableFuture.completedStage(buildResponse(200, headers));
    }

    private HttpResponse buildResponse(final int statusCode,
                                       final HttpHeaders headers) {
        final HttpResponse response = httpResponseBuilder.build();
        response.setStatus(statusCode);
        response.setOrAddHeaders(headers);
        return response;
    }
}
