package io.rxmicro.examples.validation.server.extendable.model.child_model_without_fields.parent;

import io.rxmicro.examples.validation.server.extendable.model.child_model_without_fields.grand.$$GrandParentModelToJsonConverter;
import io.rxmicro.exchange.json.detail.ModelToJsonConverter;
import io.rxmicro.json.JsonObjectBuilder;

/**
 * Generated by {@code RxMicro Annotation Processor}
 */
public final class $$ParentModelToJsonConverter extends ModelToJsonConverter<Parent> {

    private final $$GrandParentModelToJsonConverter parentConverter =
            new $$GrandParentModelToJsonConverter();

    public void putValuesToBuilder(final Parent model,
                                   final JsonObjectBuilder builder) {
        parentConverter.putValuesToBuilder(model, builder);
        builder.put("parentParameter", model.parentParameter);
    }
}
