package io.rxmicro.examples.rest.controller.params.model.nested;

import io.rxmicro.exchange.json.detail.ModelToJsonConverter;
import io.rxmicro.json.JsonObjectBuilder;

import java.util.Map;

/**
 * Generated by {@code RxMicro Annotation Processor}
 */
public final class $$NestedModelModelToJsonConverter extends ModelToJsonConverter<NestedModel> {

    @Override
    public Map<String, Object> toJsonObject(final NestedModel model) {
        final JsonObjectBuilder builder = new JsonObjectBuilder();
        putValuesToBuilder(model, builder);
        return builder.build();
    }

    public void putValuesToBuilder(final NestedModel model,
                                   final JsonObjectBuilder builder) {
        builder.put("string_parameter", model.stringParameter);
        builder.put("big_decimal_parameter", model.bigDecimalParameter);
        builder.put("instant_parameter", model.instantParameter);
    }
}
