package io.rxmicro.examples.data.r2dbc.postgresql.primary.keys.model;

import io.r2dbc.spi.Row;
import io.r2dbc.spi.RowMetadata;
import io.rxmicro.data.sql.r2dbc.detail.EntityFromR2DBCSQLDBConverter;

/**
 * Generated by {@code RxMicro Annotation Processor}
 */
public final class $$AccountEntityFromR2DBCSQLDBConverter extends EntityFromR2DBCSQLDBConverter<Row, RowMetadata, Account> {

    public Account setId(final Account model,
                         final Row dbRow,
                         final RowMetadata metadata) {
        model.id = dbRow.get(0, Long.class);
        return model;
    }
}
