package io.rxmicro.examples.processor.all.components.model;

import io.rxmicro.rest.client.detail.ClientModelReader;
import io.rxmicro.rest.client.detail.HttpResponse;

/**
 * Generated by {@code RxMicro Annotation Processor}
 */
public final class $$AccountClientModelReader extends ClientModelReader<Account> {

    private final $$AccountModelFromJsonConverter accountModelFromJsonConverter =
            new $$AccountModelFromJsonConverter();

    @Override
    public Account readSingle(final HttpResponse response) {
        return accountModelFromJsonConverter.fromJsonObject(response.getBody());
    }
}
