package io.rxmicro.examples.rest.controller.extendable.model.response.headers_only.child_model_without_fields.child;

import io.rxmicro.examples.rest.controller.extendable.model.response.headers_only.child_model_without_fields.parent.$$ParentConstraintValidator;
import io.rxmicro.model.ModelType;
import io.rxmicro.validation.ConstraintValidator;

/**
 * Generated by {@code RxMicro Annotation Processor}
 */
public final class $$ChildConstraintValidator implements ConstraintValidator<Child> {

    private final $$ParentConstraintValidator parentValidator =
            new $$ParentConstraintValidator();

    @Override
    public void validateNonNull(final Child model,
                                final ModelType httpModelType,
                                final String name) {
        parentValidator.validate(model, httpModelType, name);
    }
}
