package io.rxmicro.examples.rest.client.model.fields.params.reflection.nested;

import io.rxmicro.exchange.json.detail.ModelToJsonConverter;
import io.rxmicro.json.JsonObjectBuilder;

import java.util.Map;

import static rxmicro.$$Reflections.getFieldValue;

/**
 * Generated by rxmicro annotation processor
 *
 * @link https://rxmicro.io
 */
public final class $$NestedModelToJsonConverter extends ModelToJsonConverter<Nested> {

    @Override
    public Map<String, Object> toJsonObject(final Nested model) {
        return new JsonObjectBuilder()
                .put("value", getFieldValue(model, "value"))
                .build();
    }
}
