package rxmicro;

import java.util.Set;

import static io.rxmicro.common.CommonConstants.RX_MICRO_COMMON_MODULE;
import static io.rxmicro.common.util.Formats.format;
import static io.rxmicro.runtime.RuntimeConstants.RX_MICRO_RUNTIME_MODULE;

/**
 * Generated by {@code RxMicro Annotation Processor}
 */
public final class $$RestBasedMicroServiceTestFixer {

    static {
        final Module currentModule = $$RestBasedMicroServiceTestFixer.class.getModule();
        currentModule.addExports("rxmicro", RX_MICRO_RUNTIME_MODULE);
    }

    public $$RestBasedMicroServiceTestFixer() {
        final Module currentModule = getClass().getModule();
        if (currentModule.isNamed()) {
            System.out.println("Fix the environment for REST based microservice test(s)...");
            final Module unnamedModule = getClass().getClassLoader().getUnnamedModule();
            final Set<Module> modules = Set.of(unnamedModule, RX_MICRO_COMMON_MODULE);
            for (final Module module : modules) {
                for (final String packageName : currentModule.getPackages()) {
                    currentModule.addOpens(packageName, module);
                    System.out.println(format(
                            "opens ?/? to ?",
                            currentModule.getName(),
                            packageName,
                            module.isNamed() ? module.getName() : "ALL-UNNAMED")
                    );
                }
            }
        }
    }
}
