package io.rxmicro.examples.cdi.multibinder.impl;

import io.rxmicro.cdi.detail.BeanSupplier;

/**
 * Generated by rxmicro annotation processor
 */
public final class $$DevelopmentBusinessServiceBeanSupplier extends BeanSupplier<DevelopmentBusinessService> {

    @Override
    public DevelopmentBusinessService get() {
        return new DevelopmentBusinessService();
    }
}
