package io.rxmicro.examples.cdi.ambiguty.resolving.impl.classname.field.name.impl;

import io.rxmicro.cdi.detail.BeanSupplier;

/**
 * Generated by rxmicro annotation processor
 *
 * @link https://rxmicro.io
 */
public final class $$ProductionBusinessServiceBeanSupplier extends BeanSupplier<ProductionBusinessService> {

    @Override
    public ProductionBusinessService get() {
        return new ProductionBusinessService();
    }
}
