package io.rxmicro.examples.rest.controller.model.fields.pathvariables;

import io.rxmicro.examples.rest.controller.model.fields.Status;
import io.rxmicro.rest.model.HttpModelType;
import io.rxmicro.rest.model.PathVariableMapping;
import io.rxmicro.rest.server.detail.component.ModelReader;
import io.rxmicro.rest.server.detail.model.HttpRequest;

/**
 * Generated by rxmicro annotation processor
 *
 * @link http://rxmicro.io
 */
public final class $$VirtualVirtualPathVariablesRequestModelReader extends ModelReader<$$VirtualVirtualPathVariablesRequest> {

    @Override
    public $$VirtualVirtualPathVariablesRequest read(final PathVariableMapping pathVariableMapping,
                                                     final HttpRequest request,
                                                     final boolean readParametersFromBody) {
        final $$VirtualVirtualPathVariablesRequest model = new $$VirtualVirtualPathVariablesRequest();
        model.booleanParameter = toBoolean(pathVariableMapping.getValue("a"), HttpModelType.path, "a");
        model.byteParameter = toByte(pathVariableMapping.getValue("b"), HttpModelType.path, "b");
        model.shortParameter = toShort(pathVariableMapping.getValue("c"), HttpModelType.path, "c");
        model.intParameter = toInteger(pathVariableMapping.getValue("d"), HttpModelType.path, "d");
        model.longParameter = toLong(pathVariableMapping.getValue("e"), HttpModelType.path, "e");
        model.bigIntParameter = toBigInteger(pathVariableMapping.getValue("f"), HttpModelType.path, "f");
        model.floatParameter = toFloat(pathVariableMapping.getValue("g"), HttpModelType.path, "g");
        model.doubleParameter = toDouble(pathVariableMapping.getValue("h"), HttpModelType.path, "h");
        model.decimalParameter = toBigDecimal(pathVariableMapping.getValue("i"), HttpModelType.path, "i");
        model.charParameter = toCharacter(pathVariableMapping.getValue("j"), HttpModelType.path, "j");
        model.stringParameter = toString(pathVariableMapping.getValue("k"), HttpModelType.path, "k");
        model.instantParameter = toInstant(pathVariableMapping.getValue("l"), HttpModelType.path, "l");
        model.status = toEnum(Status.class, pathVariableMapping.getValue("m"), HttpModelType.path, "m");
        return model;
    }
}
